### PR TITLE
fix(core-clp): Construct file paths in test cases relative to test file location rather than working directory (fixes #124).

### LINKED ISSUE #124: Schema unit tests fail if run outside build directory.
### Bug

If the unit tests are run outside the build directory, e.g.:
`./build/unitTest` instead of `cd build && ./unitTest`
you will get 11 failures related to missing schema files.

This is caused by relative paths being used in the schema unit tests.

An error example:
```
/home/lion/yscope/clp-ffi-go/cpp/clp/components/core/tests/test-Grep.cpp:21: FAILED:
due to unexpected exception with message:
ReaderInterface operation failed

[2023-05-20 23:25:59.016] [info] [test-ParserWithUserSchema.cpp:72] File not found: /home/lion/yscope/clp-ffi-go/cpp/clp/components/tests/test_schema_files/missing_schema.txt
``` 

### CLP version

460d377

### Environment

ghcr.io/y-scope/clp/clp-core-dependencies-x86-ubuntu-focal:main

### Reproduction steps

1. build the latest CLP
2. run `unitTest` outside of your build directory (i.e. run `unitTest` from any directory other than the file's parent)

### PR DESCRIPTION
**Pull request by quinntaylormitchell**
# Description

Issue #124 describes how some unit tests fail if you run `unitTest` outside the build directory. The offending test cases are in `test-GrepCore.cpp` and `test-ParserWithUserSchema.cpp`.

This PR adds methods that construct file paths using the `__FILE__` macro from `std::filesystem::path`.

_NOTE: in the future we should deduplicate the code by having some directory called `test-utils` or something where we can store methods like `get_test_dir_local_path()`._

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

`unitTest` has been run from inside and outside the build directory; all test cases pass.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

- **Tests**
  - Replaced hard-coded relative test paths with centralized, dynamically resolved test directories to improve environment-independent reliability.
  - Switched test asset handling to standard filesystem utilities and standardized loading of schema and query files across suites.
  - No changes to product behaviour or user-facing functionality.

### CODE REVIEW

**Comment by quinntaylormitchell** [comment]
@coderabbitai review

**Comment by quinntaylormitchell** [comment]
I mention in the Description that we should deduplicate the code that gets local paths and store it in some directory called `test-utils` or something. Would that be appropriate for this PR?

**Comment by quinntaylormitchell** [comment]
@coderabbitai review

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 1]
```diff
@@ -28,6 +29,16 @@ using log_surgeon::SchemaParser;
...
 
+namespace {
+[[nodiscard]] auto get_test_dir_local_path() -> std::string;
+
+auto get_test_dir_local_path() -> std::string {
+    std::filesystem::path const current_file_path{__FILE__};
+    auto const tests_dir{current_file_path.parent_path()};
+    return tests_dir.string();
+}
+}  // namespace
```
[the remark this answers is not in the document]
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: waiting on advice from colleagues on whether or not it is appropriate to do that in this PR, or whether that should be saved for another PR

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 2]
```diff
@@ -183,10 +201,11 @@
 
 TEST_CASE("Test reverse lexer", "[Search]") {
     ByteLexer reverse_lexer;
-    std::string schema_file_name = "../tests/test_schema_files/search_schema.txt";
+    std::string schema_file_name
+            = get_test_dir_local_path() + "/test_schema_files/search_schema.txt";
     std::string schema_file_path = boost::filesystem::weakly_canonical(schema_file_name).string();
     load_lexer_from_file(schema_file_path, false, reverse_lexer);
-    FileReader file_reader{"../tests/test_search_queries/easy.txt"};
+    FileReader file_reader{get_test_dir_local_path() + "/test_search_queries/easy.txt"};
```
[the remark this answers is not in the document]
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: You are correct, but not sure if this is within scope of this PR.

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 3]
```diff
@@ -80,8 +91,8 @@
 }
 
 TEST_CASE("Test error for missing schema file", "[LALR1Parser][SchemaParser]") {
-    std::string file_path = "../tests/test_schema_files/missing_schema.txt";
-    std::string file_name = boost::filesystem::weakly_canonical(file_path).string();
+    std::string file_path = get_test_dir_local_path() + "/test_schema_files/missing_schema.txt";
+    // std::string file_name = boost::filesystem::weakly_canonical(file_path).string();
     REQUIRE_THROWS_WITH(
```
[the remark this answers is not in the document]
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: why do we prefer this?

**Comment by quinntaylormitchell** [comment]
@coderabbitai review

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 4]
```diff
@@ -159,10 +173,11 @@ TEST_CASE("Test creating log parser without delimiters", "[LALR1Parser][LogParse
 
 TEST_CASE("Test forward lexer", "[Search]") {
     ByteLexer forward_lexer;
-    std::string schema_file_name = "../tests/test_schema_files/search_schema.txt";
+    std::string schema_file_name
+            = (get_test_dir() / "test_schema_files/search_schema.txt").string();
     std::string schema_file_path = boost::filesystem::weakly_canonical(schema_file_name).string();
     load_lexer_from_file(schema_file_path, false, forward_lexer);
-    FileReader file_reader{"../tests/test_search_queries/easy.txt"};
+    FileReader file_reader{(get_test_dir() / "test_search_queries/easy.txt").string()};
```
[the remark this answers is not in the document]
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: outside of the scope of this PR

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 5]
```diff
@@ -79,8 +89,7 @@ void decompress(std::string archive_dir, std::string output_dir) {
 }
 
 TEST_CASE("Test error for missing schema file", "[LALR1Parser][SchemaParser]") {
-    std::string file_path = "../tests/test_schema_files/missing_schema.txt";
-    std::string file_name = boost::filesystem::weakly_canonical(file_path).string();
+    std::string file_path = (get_test_dir() / "test_schema_files/missing_schema.txt").string();
```
Comment (haiqi96) [inline components/core/tests/test-ParserWithUserSchema.cpp]: nit:
1. We can store the value of `get_test_dir()` to a variable before all TEST_CASEs so that we can reuse the variable instead of recalling the method multiple times. Since `test_schema_files` is shared by all test_files, we can put it in the shared variable as well, maybe name it as `test_schema_files_dir`.
2: we can use auto const for file_path, since `.string()` has an explicit return type.
3. we can delay calling string() till when we actually need to. 

Combine it all together, 

```
auto const test_schema_file_path{test_schema_files_dir / "empty_schema.txt"};
REQUIRE_THROWS_WITH(
            generate_schema_ast(test_schema_file_path.string()),
            "Schema:1:1: error: empty file\n"
)
```



Ditto for all other occurence. Let's always declare a test_schema_path variable, instead of directly putting a long line (such as `(get_test_dir() / "test_schema_files/search_schema.txt").string()`) into the function parameter.

File: components/core/tests/test-GrepCore.cpp [hunk 6]
```diff
@@ -17,9 +18,18 @@ using log_surgeon::SchemaParser;
...
+auto get_test_dir() -> std::filesystem::path {
+    std::filesystem::path const current_file_path{__FILE__};
+    return current_file_path.parent_path();
+}
+}  // namespace
+
 TEST_CASE("get_bounds_of_next_potential_var", "[get_bounds_of_next_potential_var]") {
     ByteLexer lexer;
-    load_lexer_from_file("../tests/test_schema_files/search_schema.txt", lexer);
+    load_lexer_from_file((get_test_dir() / "test_schema_files/search_schema.txt").string(), lexer);
```
Comment (haiqi96) [inline components/core/tests/test-GrepCore.cpp]: please make sure you test and run through linter.
```suggestion
    auto const test_schema_file_path{get_test_dir() / "test_schema_files" / "search_schema.txt"}
    load_lexer_from_file(test_schema_file_path.string(), lexer);
```

File: components/core/tests/test-ParserWithUserSchema.cpp (hunk 5 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: agreed, will do.

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 7]
```diff
@@ -79,56 +93,55 @@ void decompress(std::string archive_dir, std::string output_dir) {
...
+            generate_schema_ast(file_path.string()),
             "Schema:2:11: error: expected ':' before ' ' token\n"
             "          delimiters : \\r\\n\n"
             "                    ^\n"
     );
 }
 
 TEST_CASE("Test creating schema parser", "[LALR1Parser][SchemaParser]") {
-    generate_schema_ast("../tests/test_schema_files/easy_schema.txt");
+    generate_schema_ast((test_schema_dir / "easy_schema.txt").string());
```
Comment (haiqi96) [inline components/core/tests/test-ParserWithUserSchema.cpp]: Let's break the line into two lines for better readability. Ditto for other lines below
```suggestion
    auto const schema_file_path{test_schema_dir / "easy_schema.txt"};
    generate_schema_ast(schema_file_path.string());
```

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 8]
```diff
@@ -158,10 +171,10 @@ TEST_CASE("Test creating log parser without delimiters", "[LALR1Parser][LogParse
 
 TEST_CASE("Test lexer", "[Search]") {
     ByteLexer lexer;
-    std::string schema_file_name = "../tests/test_schema_files/search_schema.txt";
-    std::string schema_file_path = boost::filesystem::weakly_canonical(schema_file_name).string();
+    auto const schema_file_name = (test_schema_dir / "search_schema.txt").string();
+    auto const schema_file_path = boost::filesystem::weakly_canonical(schema_file_name).string();
     load_lexer_from_file(schema_file_path, lexer);
-    FileReader file_reader{"../tests/test_search_queries/easy.txt"};
+    FileReader file_reader{(test_query_dir / "easy.txt").string()};
```
Comment (haiqi96) [inline components/core/tests/test-ParserWithUserSchema.cpp]: ditto for 1 line -> 2 lines

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 9]
```diff
@@ -158,10 +171,10 @@ TEST_CASE("Test creating log parser without delimiters", "[LALR1Parser][LogParse
 
 TEST_CASE("Test lexer", "[Search]") {
     ByteLexer lexer;
-    std::string schema_file_name = "../tests/test_schema_files/search_schema.txt";
-    std::string schema_file_path = boost::filesystem::weakly_canonical(schema_file_name).string();
+    auto const schema_file_name = (test_schema_dir / "search_schema.txt").string();
+    auto const schema_file_path = boost::filesystem::weakly_canonical(schema_file_name).string();
```
Comment (haiqi96) [inline components/core/tests/test-ParserWithUserSchema.cpp]: I know you didn't write this code, but it's weird that 
1. schema_file_name is only used once.
2. filesystem::weakly_canonical should allow a `path` type argument, so I am not sure why we first convert schema_file_name to string.
3. it's not clear to me why we use `weakly_canonical` here, whereas we don't use `weakly_canonical` in other tests.

Another nit: I believe we have been trying to remove the dependency on boost::filesystem. Since you include <filesystem>, can you try replacing boost::filesystem with std::filesystem?

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 10]
```diff
@@ -79,56 +93,55 @@ void decompress(std::string archive_dir, std::string output_dir) {
 }
 
 TEST_CASE("Test error for missing schema file", "[LALR1Parser][SchemaParser]") {
-    std::string file_path = "../tests/test_schema_files/missing_schema.txt";
-    std::string file_name = boost::filesystem::weakly_canonical(file_path).string();
+    auto const file_path = test_schema_dir / "missing_schema.txt";
     REQUIRE_THROWS_WITH(
-            generate_schema_ast(file_path),
-            "Failed to read '" + file_path + "', error_code="
+            generate_schema_ast(file_path.string()),
```
Comment (haiqi96) [inline components/core/tests/test-ParserWithUserSchema.cpp]: sorry for my oversight. since we need to use file_path.string() twice for this test_case, let's store it as a separate variable
`auto const file_path_string = file_path.string()`

File: components/core/tests/test-ParserWithUserSchema.cpp (hunk 9 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: >weird

not sure!

>replacing boost::filesystem with std::filesystem

done.

Comment (haiqi96) [reply components/core/tests/test-ParserWithUserSchema.cpp]: you haven't addressed the comment on weakly_canonical, right?
I am hoping that we can rewrite the code like 
```
auto const schema_file_path = test_schema_dir / "search_schema.txt;
```
and use the path as string() where appropriate.

Looking at the doc of https://en.cppreference.com/w/cpp/filesystem/canonical.html. it seems we want to make sure there's no dot in the path. 
This leads to one question, is it possible for the return value of `get_test_dir()` (or to be more specific, `std::filesystem::path const current_file_path{__FILE__}`) to contain any dot or dot-dot element?

Quickly looking at __FILE__, it seems there's no guarantee it would not contain dot or dot-dot.

So I think what we can make everything simple, convert the return value of get_test_dir() into absolute path by using std::filesystem::canonical(). Imo, it is also safer to return the absolute path.

File: components/core/tests/test-GrepCore.cpp [hunk 11]
```diff
@@ -17,9 +18,22 @@ using log_surgeon::SchemaParser;
...
+namespace {
+[[nodiscard]] auto get_test_dir() -> std::filesystem::path;
+
+auto get_test_dir() -> std::filesystem::path {
+    std::filesystem::path const current_file_path{__FILE__};
+    return current_file_path.parent_path();
+}
+
+auto const test_dir = get_test_dir();
+auto const test_schema_dir = test_dir / "test_schema_files";
```
Comment (kirkrodrigues) [inline components/core/tests/test-GrepCore.cpp]: clang-tidy complains about these lines:

> Clang-Tidy: Initialization of 'test_dir' with static storage duration may throw an exception that cannot be caught.

Can we move them into the actual test case?

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 12]
```diff
@@ -28,6 +28,19 @@ using log_surgeon::SchemaAST;
 using log_surgeon::SchemaVarAST;
 using log_surgeon::Token;
 
+namespace {
+[[nodiscard]] auto get_test_dir() -> std::filesystem::path;
+
+auto get_test_dir() -> std::filesystem::path {
+    std::filesystem::path const current_file_path{__FILE__};
+    return std::filesystem::canonical(current_file_path.parent_path());
```
Comment (kirkrodrigues) [inline components/core/tests/test-ParserWithUserSchema.cpp:38]: If we're using `canonical` here, maybe do the same in the other file?

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 13]
```diff
@@ -28,6 +28,19 @@ using log_surgeon::SchemaAST;
...
+}
+
+auto const test_dir = get_test_dir();
+auto const test_schema_dir = test_dir / "test_schema_files";
+auto const test_query_dir = test_dir / "test_search_queries";
```
Comment (kirkrodrigues) [inline components/core/tests/test-ParserWithUserSchema.cpp]: Ditto about clang-tidy.

Since we reuse some of these values in multiple cases, can we change them into functions instead?

File: components/core/tests/test-GrepCore.cpp [hunk 14]
```diff
@@ -17,9 +18,22 @@ using log_surgeon::SchemaParser;
 using log_surgeon::SchemaVarAST;
 using std::string;
 
+namespace {
+[[nodiscard]] auto get_test_dir() -> std::filesystem::path;
+
+auto get_test_dir() -> std::filesystem::path {
```
Comment (kirkrodrigues) [inline components/core/tests/test-GrepCore.cpp]: How about `get_tests_dir`? `get_test_dir` sounds like it might be a function to get a testing directory.

File: components/core/tests/test-GrepCore.cpp [hunk 15]
```diff
@@ -17,9 +18,22 @@ using log_surgeon::SchemaParser;
...
+    std::filesystem::path const current_file_path{__FILE__};
+    return current_file_path.parent_path();
+}
+
+auto const test_dir = get_test_dir();
```
Comment (kirkrodrigues) [inline components/core/tests/test-GrepCore.cpp]: Ditto about naming.

File: components/core/tests/test-GrepCore.cpp (hunk 11 above)
Comment (kirkrodrigues) [inline components/core/tests/test-GrepCore.cpp]: How about `test_schema_files_dir`?

File: components/core/tests/test-ParserWithUserSchema.cpp (hunk 13 above)
Comment (kirkrodrigues) [inline components/core/tests/test-ParserWithUserSchema.cpp]: How about `test_queries_dir`?

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 16]
```diff
@@ -79,56 +92,59 @@ void decompress(std::string archive_dir, std::string output_dir) {
...
+            generate_schema_ast(file_path.string()),
             "Schema:2:11: error: expected ':' before ' ' token\n"
             "          delimiters : \\r\\n\n"
             "                    ^\n"
     );
 }
 
 TEST_CASE("Test creating schema parser", "[LALR1Parser][SchemaParser]") {
-    generate_schema_ast("../tests/test_schema_files/easy_schema.txt");
+    auto const schema_file_path{test_schema_dir / "easy_schema.txt"};
```
Comment (kirkrodrigues) [inline components/core/tests/test-ParserWithUserSchema.cpp]: I won't complain if someone wants to use `auto ... =` compared to `auto ...{...}`, but we should be consistent. Which one would you prefer to use?

File: components/core/tests/test-GrepCore.cpp (hunk 14 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-GrepCore.cpp]: agreed

File: components/core/tests/test-GrepCore.cpp (hunk 15 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-GrepCore.cpp]: agreed

File: components/core/tests/test-ParserWithUserSchema.cpp (hunk 12 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp:38]: agreed, forgot about that thank you

File: components/core/tests/test-GrepCore.cpp (hunk 11 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-GrepCore.cpp]: definitely

Comment (quinntaylormitchell) [reply components/core/tests/test-GrepCore.cpp]: agreed

File: components/core/tests/test-ParserWithUserSchema.cpp (hunk 13 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: agreed

File: components/core/tests/test-ParserWithUserSchema.cpp (hunk 16 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: I prefer `auto ... =` because it's what I'm used to; I think I used `auto ...{...}` because Haiqi suggested it, but then I forgot to change the others. I will use `auto ... =` for now.

File: components/core/tests/test-ParserWithUserSchema.cpp (hunk 13 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: definitely

File: components/core/tests/test-GrepCore.cpp [hunk 17]
```diff
@@ -17,9 +18,21 @@ using log_surgeon::SchemaParser;
...
+
+auto get_tests_dir() -> std::filesystem::path {
+    std::filesystem::path const current_file_path{__FILE__};
+    return std::filesystem::canonical(current_file_path.parent_path());
+}
+}  // namespace
+
 TEST_CASE("get_bounds_of_next_potential_var", "[get_bounds_of_next_potential_var]") {
+    auto const tests_dir = get_tests_dir();
+    auto const test_schema_files_dir = tests_dir / "test_schema_files";
```
Comment (kirkrodrigues) [inline components/core/tests/test-GrepCore.cpp]:
```suggestion
    auto const test_schema_files_dir = get_tests_dir() / "test_schema_files";
```

File: components/core/tests/test-GrepCore.cpp [hunk 18]
```diff
@@ -17,9 +18,21 @@ using log_surgeon::SchemaParser;
...
     ByteLexer lexer;
```
Comment (kirkrodrigues) [inline components/core/tests/test-GrepCore.cpp]: Nit: Can we move this one line lower so that the order of the variable declarations matches the function's arguments?

File: components/core/tests/test-ParserWithUserSchema.cpp [hunk 19]
```diff
@@ -158,10 +181,10 @@ TEST_CASE("Test creating log parser without delimiters", "[LALR1Parser][LogParse
...
 TEST_CASE("Test lexer", "[Search]") {
     ByteLexer lexer;
-    std::string schema_file_name = "../tests/test_schema_files/search_schema.txt";
-    std::string schema_file_path = boost::filesystem::weakly_canonical(schema_file_name).string();
-    load_lexer_from_file(schema_file_path, lexer);
-    FileReader file_reader{"../tests/test_search_queries/easy.txt"};
+    auto const schema_file_path = get_test_schema_files_dir() / "search_schema.txt";
+    load_lexer_from_file(schema_file_path.string(), lexer);
+    auto const query_file_path = get_test_queries_dir() / "easy.txt";
+    FileReader file_reader = query_file_path.string();
```
Comment (kirkrodrigues) [inline components/core/tests/test-ParserWithUserSchema.cpp]: This isn't an `auto` case, right?

File: components/core/tests/test-GrepCore.cpp (hunk 17 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-GrepCore.cpp]: agreed

File: components/core/tests/test-GrepCore.cpp (hunk 18 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-GrepCore.cpp]: definitely

File: components/core/tests/test-ParserWithUserSchema.cpp (hunk 19 above)
Comment (quinntaylormitchell) [reply components/core/tests/test-ParserWithUserSchema.cpp]: sorry, what's this referring to?

Comment (kirkrodrigues) [reply components/core/tests/test-ParserWithUserSchema.cpp]: It should be the below, right?

```suggestion
    FileReader file_reader{query_file_path.string()};
```
