### PR TITLE
fix(webui): Respect case sensitivity setting in search queries (fixes #1060); refactor Zustand usages.

### LINKED ISSUE #1060: [new-webui] Case-sensitivity toggle doesn't seem to affect the query.
### Bug

As the title says. Confirmed that the query in `job_config` in the `query_jobs` table consistently had `"ignore_case": false` no matter what the state of the case sensitivity toggle was. 

### CLP version

3520895

### Environment

* Firefox 140.0.2 (64-bit) or Chrome 137.0.7151.120 (Official Build) (64-bit)

### Reproduction steps

* Compress the hive-24hrs dataset.
  ```
  sbin/start-clp.sh
  sbin/compress.sh logs/hive-24hrs/
  ```
* Open the webui
* Run the query `DESERIALIZE_ERRORs` and observe that it doesn't find any results.
* Click the case-sensitivity toggle and re-run the query. Observe that it doesn't find any results.

### PR DESCRIPTION
**Pull request by davemarco**
# Description

Case sensitivity option was submitted as part of query, this PR adds missing option.

I also did some minor refactoring per new zustand guidelines in affected files

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

Tested case sensitivity toggle works

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

* **Refactor**
  * Enhanced search controls and results timeline to dynamically respect case sensitivity settings, improving search precision while maintaining the existing user interface.

### CODE REVIEW

File: components/webui/client/src/pages/SearchPage/SearchControls/QueryInput/index.tsx [hunk 1]
```diff
@@ -21,13 +21,11 @@ import {
...
-        queryIsCaseSensitive,
-        updateQueryString,
-        updateQueryIsCaseSensitive,
-        searchUiState,
-    } = useSearchStore();
+    const queryString = useSearchStore((state) => state.queryString);
+    const queryIsCaseSensitive = useSearchStore((state) => state.queryIsCaseSensitive);
+    const updateQueryString = useSearchStore((state) => state.updateQueryString);
+    const updateQueryIsCaseSensitive = useSearchStore((state) => state.updateQueryIsCaseSensitive);
+    const searchUiState = useSearchStore((state) => state.searchUiState);
```
Comment (junhaoliao) [inline components/webui/client/src/pages/SearchPage/SearchControls/QueryInput/index.tsx]: 1. let's try to alphabetize the state retreivals
2. for actions whose definitions usually won't change, let's retrieve them non-reactively
```suggestion
    const queryIsCaseSensitive = useSearchStore((state) => state.queryIsCaseSensitive);
    const queryString = useSearchStore((state) => state.queryString);
    const searchUiState = useSearchStore((state) => state.searchUiState);

```

...
```
    const handleCaseSensitiveChange = useCallback((newValue: boolean) => {
        const {updateQueryIsCaseSensitive} = useSearchStore.getState();
        updateQueryIsCaseSensitive(newValue);
    }, []);

    const handleChange = useCallback((ev: ChangeEvent<HTMLInputElement>) => {
        const {updateQueryString} = useSearchStore.getState();
        updateQueryString(ev.target.value);
    }, []);
```

```
        <QueryBox
            isCaseSensitive={queryIsCaseSensitive}
            placeholder={"Enter your query"}
            progress={pseudoProgress}
            size={"large"}
            value={queryString}
            disabled={
                searchUiState === SEARCH_UI_STATE.QUERY_ID_PENDING ||
                searchUiState === SEARCH_UI_STATE.QUERYING
            }
            onCaseSensitiveChange={handleCaseSensitiveChange}
            onChange={handleChange}/>
```

File: components/webui/client/src/pages/SearchPage/SearchControls/SearchButton/SubmitButton.tsx [hunk 2]
```diff
@@ -19,7 +19,11 @@ import styles from "./index.module.css";
  * @return
  */
 const SubmitButton = () => {
-    const {searchUiState, timeRange, queryString, updateTimelineConfig} = useSearchStore();
+    const searchUiState = useSearchStore((state) => state.searchUiState);
+    const timeRange = useSearchStore((state) => state.timeRange);
+    const queryString = useSearchStore((state) => state.queryString);
+    const updateTimelineConfig = useSearchStore((state) => state.updateTimelineConfig);
+    const queryIsCaseSensitive = useSearchStore((state) => state.queryIsCaseSensitive);
```
Comment (junhaoliao) [inline components/webui/client/src/pages/SearchPage/SearchControls/SearchButton/SubmitButton.tsx]: 1. ditto: order
2. ditto: action retrieval
```suggestion
    const queryIsCaseSensitive = useSearchStore((state) => state.queryIsCaseSensitive);
    const queryString = useSearchStore((state) => state.queryString);
    const searchUiState = useSearchStore((state) => state.searchUiState);
    const timelineConfig = useSearchStore((state) => state.timelineConfig);
```
...
```
    const handleTimelineZoom = useCallback((newTimeRange: [Dayjs, Dayjs]) => {
        const newTimelineConfig: TimelineConfig = computeTimelineConfig(newTimeRange);

        // Update range picker selection to match zoomed range.
        const {
            updateTimeRange, updateTimeRangeOption, updateTimelineConfig,
        } = useSearchStore.getState();

        updateTimeRange(newTimeRange);
        updateTimeRangeOption(TIME_RANGE_OPTION.CUSTOM);
        updateTimelineConfig(newTimelineConfig);

        const isQueryStringEmpty = queryString === SEARCH_STATE_DEFAULT.queryString;
        if (isQueryStringEmpty) {
            return;
        }

        handleQuerySubmit({
            ignoreCase: false === queryIsCaseSensitive,
            queryString: queryString,
            timeRangeBucketSizeMillis: newTimelineConfig.bucketDuration.asMilliseconds(),
            timestampBegin: newTimeRange[0].valueOf(),
            timestampEnd: newTimeRange[1].valueOf(),
        });
    }, [
        queryIsCaseSensitive,
        queryString,
    ]);
```
(also move `handleTimelineZoom` to show up before the `useEffect()` block)

File: components/webui/client/src/pages/SearchPage/SearchResults/SearchResultsTimeline/index.tsx [hunk 3]
```diff
@@ -19,15 +19,16 @@ import {computeTimelineConfig} from "./utils";
...
+    const queryString = useSearchStore((state) => state.queryString);
+    const updateTimeRange = useSearchStore((state) => state.updateTimeRange);
+    const updateTimeRangeOption = useSearchStore((state) => state.updateTimeRangeOption);
+    const timelineConfig = useSearchStore((state) => state.timelineConfig);
+    const searchUiState = useSearchStore((state) => state.searchUiState);
+    const updateTimelineConfig = useSearchStore((state) => state.updateTimelineConfig);
+    const updateNumSearchResultsTimeline = useSearchStore(
+        (state) => state.updateNumSearchResultsTimeline
+    );
+    const queryIsCaseSensitive = useSearchStore((state) => state.queryIsCaseSensitive);
```
Comment (junhaoliao) [inline components/webui/client/src/pages/SearchPage/SearchResults/SearchResultsTimeline/index.tsx]:
```suggestion
    const queryString = useSearchStore((state) => state.queryString);
    const queryIsCaseSensitive = useSearchStore((state) => state.queryIsCaseSensitive);
    const searchUiState = useSearchStore((state) => state.searchUiState);
    const timeRange = useSearchStore((state) => state.timeRange);
```
...
```
    const handleSubmitButtonClick = useCallback(() => {
        // Update timeline to match range picker selection.
        const newTimelineConfig = computeTimelineConfig(timeRange);
        const {updateTimelineConfig} = useSearchStore.getState();
        updateTimelineConfig(newTimelineConfig);

        handleQuerySubmit({
            ignoreCase: false === queryIsCaseSensitive,
            queryString: queryString,
            timeRangeBucketSizeMillis: newTimelineConfig.bucketDuration.asMilliseconds(),
            timestampBegin: timeRange[0].valueOf(),
            timestampEnd: timeRange[1].valueOf(),
        });
    }, [
        queryString,
        queryIsCaseSensitive,
        timeRange,
    ]);
```

**Review by junhaoliao — CHANGES_REQUESTED** [review]
for the PR title, how about:
```
fix(webui): Respect case sensitivity setting in search queries (fixes #1060); refactor Zustand usages.
```

**Review by junhaoliao — APPROVED** [review]
