### PR TITLE
fix(core): Resolve clang-tidy violations and compilation errors in `GlobalMetadataDBConfig.hpp` (fixes #643).

### LINKED ISSUE #643: `GlobalMetadataDBConfig.hpp` fails to compile with GCC 13.
### Bug

https://github.com/y-scope/clp/blob/329edf66e8d368de3070ba266fcf653060fd1541/components/core/src/clp/GlobalMetadataDBConfig.hpp#L13 references `uint8_t`; however, such reference no longer exists in GCC 13 according to https://gcc.gnu.org/gcc-13/porting_to.html#:~:text=Header%20dependency%20changes
> Header dependency changes
>Some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. As such, C++ programs that used standard library components without including the right headers will no longer compile.
>
>The following headers are used less widely in libstdc++ and may need to be included explicitly when compiling with GCC 13:
>
>`<string> (for std::string, std::to_string, std::stoi etc.)`
>`<system_error> (for std::error_code, std::error_category, std::system_error).`
>`<cstdint> (for std::int8_t, std::int32_t etc.)`
>`<cstdio> (for std::printf, std::fopen etc.)`
>`<cstdlib> (for std::strtol, std::malloc etc.)`

### CLP version

329edf66e8d368de3070ba266fcf653060fd1541

### Environment

```
junhao@GIGABYTE:~/workspace/checkinstall$ gcc --version
gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

junhao@GIGABYTE:~/workspace/checkinstall$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
junhao@GIGABYTE:~/workspace/checkinstall$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

### Reproduction steps

In an environment where GCC 13 is installed (e.g., Ubuntu 2404), follow https://docs.yscope.com/clp/main/dev-guide/building-package.html#build to build the package.

### PR DESCRIPTION
**Pull request by Bill-hbrhbr**
# Description

Currently, the two files listed in the PR title create compilation issues (missing headers) in the following environment:
* WSL 1
* Ubuntu-Focal 20.04
* gcc13
* g++13

Hence, this PR clang-tidies the problematic files and removes them from the clang-tidy exclude list.

image

This PR fixes #643 and contributes to #764

# Checklist

* [X] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [X] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [X] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

* [X] Refactor PR. Unit tests still pass.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

- **Refactor**
  - Modernised configuration handling with updated default settings and enhanced return value assurance for getter methods, improving consistency and reliability.

- **Chore**
  - Streamlined code quality tasks by removing outdated components from automated checks, contributing to smoother project maintenance.

### CODE REVIEW

File: components/core/src/clp/GlobalMetadataDBConfig.hpp [hunk 1]
```diff
@@ -16,34 +17,43 @@ class GlobalMetadataDBConfig {
...
 
-    std::string const& get_metadata_table_prefix() const { return m_metadata_table_prefix; }
+    [[nodiscard]] auto get_metadata_table_prefix() const -> std::string const& {
+        return m_metadata_table_prefix;
+    }
 
 private:
     // Variables
-    MetadataDBType m_metadata_db_type;
+    static constexpr int cDefaultMetadataDbPort = 3306;
```
Comment (kirkrodrigues) [inline components/core/src/clp/GlobalMetadataDBConfig.hpp:51]:
```suggestion
    constexpr int cDefaultMetadataDbPort{3306};
```

Don't think the `static` is necessary, right?

File: components/core/src/glt/GlobalMetadataDBConfig.hpp [hunk 2]
```diff
@@ -16,34 +17,43 @@ class GlobalMetadataDBConfig {
...
 
-    std::string const& get_metadata_table_prefix() const { return m_metadata_table_prefix; }
+    [[nodiscard]] auto get_metadata_table_prefix() const -> std::string const& {
+        return m_metadata_table_prefix;
+    }
 
 private:
     // Variables
-    MetadataDBType m_metadata_db_type;
+    static constexpr int cDefaultMetadataDbPort = 3306;
```
Comment (kirkrodrigues) [inline components/core/src/glt/GlobalMetadataDBConfig.hpp:51]:
```suggestion
    constexpr int cDefaultMetadataDbPort{3306};
```

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]
For the PR title, how about:

```
fix(core): Resolve clang-tidy violations and compilation errors in GlobalMetadataConfig.hpp (fixes #643).
```

File: components/core/src/clp/GlobalMetadataDBConfig.hpp (hunk 1 above)
Comment (Bill-hbrhbr) [reply components/core/src/clp/GlobalMetadataDBConfig.hpp]: @kirkrodrigues It's necessary to resolve the following compile error
`error: non-static data member ‘cDefaultMetadataDbPort’ declared ‘constexpr’`

Comment (Bill-hbrhbr) [reply components/core/src/clp/GlobalMetadataDBConfig.hpp]: I've undone the suggested fixes

Comment (kirkrodrigues) [reply components/core/src/clp/GlobalMetadataDBConfig.hpp:51]: > It's necessary to resolve the following compile error

Gotcha, my mistake.

> I've undone the suggested fixes

Why undo the brace init?

Comment (Bill-hbrhbr) [reply components/core/src/clp/GlobalMetadataDBConfig.hpp]: right my bad. updated just now

**Review by kirkrodrigues — APPROVED** [review]
