### PR TITLE
clp-s: Handle cases where clp-string query-parsing falls back to decompress + match (fixes #403).

### LINKED ISSUE #403: clp-s: Incorrect search results with a wildcard character in the middle of a query
### Bug

When using clp-s to search for a log-text with a wildcard query, if a wildcard is positioned the middle, it may return empty results despite the existence of matching results.

### CLP version

3e95aafe132cd713169acf79cd15f7c13a63cabd

### Environment

MacOS 13.2.1

### Reproduction steps

Compress the following log and run the query `a: *He*lo*`, the results are empty.
```
{"a": "Hello world?", "b": 1, "c":"*"}
{"a": "Hello *", "b": "?world"}
```

### PR DESCRIPTION
**Pull request by wraymo**
# References

#403

# Description

Previously, when a query did not contain a subquery, it was not evaluated in clp-s. However, in cases where `matchability = SubQueryMatchabilityResult::SupercedesAllSubQueries`, this caused an issue. This PR fixes the bug, which indirectly resolves issue #403. The primary code change aligns clp-s with the behavior of clp in `Grep::process_raw_query`. The relevant code in `clp_s/search/Output.cpp` has also been updated.

# Validation performed

+ Validated the example in #403, the query returned all matching results.
+ Compressed first 1,000,000 log messages of [mongodb](https://zenodo.org/records/10516285) dataset. Executed queries below that targets a log-text field:
  ```
  msg: "*wire *"
  attr.message.msg: log_remove*
  attr.message.msg: "*id 1*"
  attr.message.msg: "*journal/WiredTigerLog*LSN*3456*"
  ```
  The query results remain unchanged after the code change.

### CODE REVIEW

File: components/core/src/clp_s/search/clp_search/Grep.cpp [hunk 1]
```diff
@@ -446,12 +440,6 @@ bool Grep::process_raw_query(
     while (get_bounds_of_next_potential_var(processed_search_string, begin_pos, end_pos, is_var)) {
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/clp_search/Grep.cpp:440]: I think we can get rid of the `FIXME` on the lines above?

File: components/core/src/clp_s/search/clp_search/Grep.cpp [hunk 2]
```diff
@@ -471,31 +459,28 @@ bool Grep::process_raw_query(
     // - (token1 as logtype) (token2 as var)
     // - (token1 as var) (token2 as logtype)
     // - (token1 as var) (token2 as var)
-    SubQuery sub_query;
+
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/clp_search/Grep.cpp:462]:
```suggestion
```

File: components/core/src/clp_s/search/clp_search/Grep.cpp [hunk 3]
```diff
@@ -471,31 +459,28 @@ bool Grep::process_raw_query(
...
+    vector<SubQuery> sub_queries;
     string logtype;
     bool type_of_one_token_changed = true;
     while (type_of_one_token_changed) {
-        sub_query.clear();
-
+        SubQuery sub_query;
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/clp_search/Grep.cpp:467]:
```suggestion
        SubQuery sub_query;

```

File: components/core/src/clp_s/search/Output.cpp [hunk 4]
```diff
@@ -1,18 +1,15 @@
...
-#include <regex>
-#include <stack>
+#include <memory>
+#include <vector>
 
 #include "../../clp/type_utils.hpp"
-#include "../ArchiveReader.hpp"
-#include "../FileWriter.hpp"
-#include "../ReaderUtils.hpp"
-#include "../Utils.hpp"
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/Output.cpp:10]: I think `StringUtils` still needs this as a direct include.

File: components/core/src/clp_s/search/Output.cpp [hunk 5]
```diff
@@ -474,21 +472,31 @@ bool Output::evaluate_clp_string_filter(
...
+                    }
+                    break;
                 }
-                break;
             }
+        } else {
+            std::string const decompressed_message
+                    = std::get<std::string>(reader->extract_value(m_cur_message));
+            matched = StringUtils::wildcard_match_unsafe(
+                    decompressed_message,
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/Output.cpp:496]:
```suggestion
            matched = StringUtils::wildcard_match_unsafe(
                    std::get<std::string>(reader->extract_value(m_cur_message)),
```

File: components/core/src/clp_s/search/Output.cpp [hunk 6]
```diff
@@ -474,21 +472,31 @@ bool Output::evaluate_clp_string_filter(
...
-                } else {
-                    matched = true;
+        if (q->contains_sub_queries()) {
+            for (auto const& subquery : q->get_sub_queries()) {
+                if (subquery.matches_logtype(id) && subquery.matches_vars(vars)) {
+                    if (subquery.wildcard_match_required()) {
+                        std::string const decompressed_message
+                                = std::get<std::string>(reader->extract_value(m_cur_message));
+                        matched = StringUtils::wildcard_match_unsafe(
+                                decompressed_message,
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/Output.cpp:482]:
```suggestion
                        matched = StringUtils::wildcard_match_unsafe(
                                std::get<std::string>(reader->extract_value(m_cur_message)),
```

File: components/core/src/clp_s/search/Output.cpp [hunk 7]
```diff
@@ -887,23 +894,26 @@ void Output::populate_string_queries(std::shared_ptr<Expression> const& expr) {
...
                         m_var_dict,
                         query_string,
                         m_ignore_case,
-                        q,
                         false
-                );
+                ));
             } else {
-                Grep::process_raw_query(m_log_dict, m_var_dict, query_string, m_ignore_case, q);
+                m_string_query_map[query_string] = Grep::process_raw_query(
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/Output.cpp:911]: I think once you fix the conflict, this line will be gone, but we should use std::move here too.

File: components/core/src/clp_s/search/Output.cpp [hunk 8]
```diff
@@ -887,23 +894,26 @@ void Output::populate_string_queries(std::shared_ptr<Expression> const& expr) {
...
             // search on log type dictionary
-            Query& q = m_string_query_map[query_string];
             if (query_string.find("*") != std::string::npos
                 || filter->get_column()->matches_type(LiteralType::VarStringT))
             {
                 // if it matches VarStringT then it contains no space, so we
                 // don't't add more wildcards. Likewise if it already contains some wildcards
                 // we do not add more
-                Grep::process_raw_query(
+                m_string_query_map[query_string] = std::move(Grep::process_raw_query(
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/Output.cpp:903]: Shall we switch to `emplace` instead?

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]
Nice work. A few minor comments.

**Review by kirkrodrigues — APPROVED** [review]
One small suggestion.

For the PR title, how about:

clp-s: Handle cases where clp-string query-parsing falls back to decompress + match (fixes #403).

**Review by kirkrodrigues — APPROVED** [review]
