### PR TITLE
fix(lib_install): Disable file system translation in `checkinstall` during dependency installation (fixes #642).

### LINKED ISSUE #642: On Ubuntu 24.04, lib_install scripts that rely on checkinstall fail to run.
### Bug

as the title says.
e.g.,
```
junhao@GIGABYTE:~/workspace/clp/components/core/tools/scripts/lib_install$ sudo ./fmtlib.sh 8.0.1
...
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libfmt.a
CMake Error at cmake_install.cmake:46 (file):
  file INSTALL cannot copy file
  "/tmp/fmtlib-installation/fmt-8.0.1/cmake-build-release/libfmt.a" to
  "/usr/local/lib/libfmt.a": No such file or directory.


make: *** [Makefile:130: install] Error 1

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.

```

### CLP version

329edf66e8d368de3070ba266fcf653060fd1541

### Environment

```
junhao@GIGABYTE:~$ uname -a
Linux GIGABYTE 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
junhao@GIGABYTE:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
junhao@GIGABYTE:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

### Reproduction steps

1. `cd ~/workspace/clp/components/core/tools/scripts/lib_install`
2. `sudo ./fmtlib.sh 8.0.1`

### PR DESCRIPTION
**Pull request by junhaoliao**
# Description

1. Disable file system translation in `checkinstall` during dependency installation.
2. Streamline install commands composition.

# Validation performed

1. Entered an environment where GCC 13 is installed (e.g., Ubuntu 2404)
2. Followed https://docs.yscope.com/clp/main/dev-guide/building-package.html#:~:text=Install%20CLP%20core%E2%80%99s%20dependencies to install CLP's core dependencies.
3. Observed successful installations for all dependencies.

## Summary by CodeRabbit

- **New Features**
	- Enhanced command execution structure for installation scripts, improving flexibility and clarity.
	- Added support for `checkinstall` with structured command arguments across multiple scripts.

- **Bug Fixes**
	- Improved error handling and checks for the existence of necessary directories and files during installation.

- **Refactor**
	- Replaced `privileged_command_prefix` with `install_cmd_args` array in multiple scripts for better command management.

### CODE REVIEW

**Comment by Bill-hbrhbr** [comment]
I don't know if this falls into the scope of the PR. 
The install script of `liblzma` has just been added, could you also upgrade it to use the new `checkinstall` script? Thanks~

**Comment by junhaoliao** [comment]
> I don't know if this falls into the scope of the PR. The install script of `liblzma` has just been added, could you also upgrade it to use the new `checkinstall` script? Thanks~

sure. thanks for the heads-up!

**Comment by junhaoliao** [comment]
@Bill-hbrhbr i just added `checkinstall` for the `lib_install/liblzma.sh` script. I ran the dependency installation script `clp/components/core/tools/scripts/lib_install/ubuntu-jammy/install-all.sh ` then ran `task` and observed no failure. Let me know if there's anything else i need to check.

File: components/core/tools/scripts/lib_install/liblzma.sh [hunk 1]
```diff
@@ -60,7 +75,30 @@ mkdir build
...
+    --fstrans=no
+    --nodoc
+    --pkgname "${package_name}"
+    --pkgversion "${version}"
+    --provides "${package_name}"
+    --pakdir "${deb_output_dir}"
+  )
+fi
+install_cmd_args+=(
+    make install liblzma
```
Comment (Bill-hbrhbr) [inline components/core/tools/scripts/lib_install/liblzma.sh:99]:
```suggestion
    make install
```

Comment (Bill-hbrhbr) [reply components/core/tools/scripts/lib_install/liblzma.sh:99]: Thanks for the update. Also, I'm pretty sure the `liblzma` at the end here is superfluous.
Otherwise, I don't have further comments unless someone asks me to review the details of the bash scripts

**Review by kirkrodrigues — APPROVED** [review]
