### PR TITLE
clp-s: Fix search bug caused by NarrowTypes (fixes #254)

### LINKED ISSUE #254: Schema matching fails on query with negated varstring and clpstring filters on same key
### Bug

For the following data
```
{"a": "clp string"}
{"a": "string clp"}
```

The query `NOT a: "clp string"` will return the second record, but the query `NOT (a: "clp string" OR a: "b")` will fail schema matching and return no records.

The AST for the failing case is `AndExpr(!FilterExpr(EQ, ColumnDescriptor<clpstring,array>("a"), "clp string"), !FilterExpr(EQ, ColumnDescriptor<varstring,array>("a"), "b"))`

The problem is that since the dataset contains no `varstring` type column the second filter fails column matching, gets replaced with `EmptyExpr`, and the entire `AndExpr` gets constant propagated away. This bug is a bit annoying, because while the `varstring` column "a" doesn't exist the JSON string column "a" *does* exist.

The expected behaviour is to treat the filter as `False` on the `clpstring` column "a" when it *does* exist (and the inverted filter as true).

Actually, for every string that matches either strictly `varstring` or `clpstring` there should be an implicit negated condition on the existence of the other type.

For example `a<clpstring> NEQ "a b"` -> `a<clpstring> EQ "a b" OR EXISTS a<varstring>`
and similarly `a<varstring> NEQ "b" -> `a<varstring> NEQ "b" OR EXISTS a<clpstring>`.

This edge case only applies for negated conditions -- something that *does not match* a particular `clpstring` will *not match* every `varstring`, but something that *does match* a particular clpstring will *never match* a `varstring.

Easiest way to handle this edge case is probably by either augmenting the AST during either ConvertToExists or in another pass, or by very careful treatment during Schema Matching.

### CLP version

9e6b75581421ddcd3473d6886fd4acaf23698603

### Environment

Ubuntu focal docker image

### Reproduction steps

1) Ingest example data above
2) Run example query

### PR DESCRIPTION
**Pull request by gibber9809**
# References
Fixes #254 

# Description
This PR fixes a bug in NarrowTypes where we weren't considering an edge case involving not equals operations on string columns. See #254 for more details.

The fix also includes an optimization to avoid blowing up the AST for long not equals clauses on the same column.

# Validation performed
* Validated that search works correctly for the toy example in #254 
* Validated that search returns correct results for more complicated queries on larger datasets
* Validated that the included optimization helps maintain smaller AST size

### CODE REVIEW

**Review by wraymo — DISMISSED** [review]
Great PR! One minor thing is about how we initialize values. I guess for class members we will use `{}`, but for variables declared in a function, I'm not sure if we want to follow the same style. Other than that, it looks good to me.

File: components/core/src/clp_s/search/ColumnDescriptor.hpp [hunk 1]
```diff
@@ -56,6 +56,13 @@ class DescriptorToken {
      */
     std::string const& get_token() const { return m_token; }
 
+    /**
+     * Equal to operator to allow comparison between descriptor tokens.
+     * @return true if this token is equal to right hand side
+     * @return false if this token is not equal to the right hand side
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/ColumnDescriptor.hpp:62]:
```suggestion
     * @return Whether this token is equal to the given token
```

* Alternatively, I think we could drop this docstring since it doesn't add much.
* Minor, but you could add a comment in the method saying that `m_wildcard` and `m_regex` are properties derived from `m_token`, so that's why we only need to compare `m_token`.

File: components/core/src/clp_s/search/ColumnDescriptor.hpp [hunk 2]
```diff
@@ -188,6 +195,13 @@ class ColumnDescriptor : public Literal {
 
     bool matches_exactly(LiteralTypeBitmask mask) override { return m_flags == mask; }
 
+    /**
+     * Equal to operator to allow comparison between two column descriptors.
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/ColumnDescriptor.hpp:199]: Ditto comment about docstring.

File: components/core/src/clp_s/search/NarrowTypes.cpp [hunk 3]
```diff
@@ -67,6 +84,50 @@ std::shared_ptr<Expression> NarrowTypes::narrow(std::shared_ptr<Expression> cur)
...
+         * Fix for bug #254
+         * If a filtering operation which can originally match a clp string and a var string is
+         * narrowed to just one of those underlying types AND the filter is performing a not equals
+         * operation then we need to replace the filter with an OR across that filter expression,
+         * and an EXISTS expression for the other underlying type.
+         *
+         * This is because if we are trying to see if some value is not equal to a specific variable
+         * string we can guarantee that every clp string is not equal to that specific variable
+         * string (because that variable string must not contain a space, but any clp string must).
+         * The reverse is true for checking if some value matches a specific clp string.
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/NarrowTypes.cpp:98]:
```suggestion
         * Fix for bug y-scope/clp#254.
         * If:
         * - a filtering operation that can match a clp string and a var string is narrowed to just
         *   one of those underlying types
         * - AND the filter is performing a not equals operation
         * then we need to replace the filter with an OR across:
         * - the filter expression
         * - and an EXISTS expression for the other underlying type.
         *
         * This is because if we are trying to determine if some value is not equal to a specific
         * variable string, we can guarantee that every clp string is not equal to that specific
         * variable string (because that variable string must not contain a space, but any clp
         * string must). The reverse is true for checking if some value matches a specific clp
         * string.
```

File: components/core/src/clp_s/search/NarrowTypes.cpp [hunk 4]
```diff
@@ -67,6 +84,50 @@ std::shared_ptr<Expression> NarrowTypes::narrow(std::shared_ptr<Expression> cur)
...
+                    = narrowed_clp_string ? LiteralType::ClpStringT : LiteralType::VarStringT;
+            auto exists_column = filter->get_column()->copy();
+            exists_column->set_matching_type(exists_column_type);
+
+            // This is an optimization to avoid creating multiple equivalent expressions in this
+            // subtree of the AST. If the user has specified a long list of not equals expressions
+            // on the same column (as is common when someone tries filter out e.g. a long list of
+            // UUIDs) then we only need to transform one filter expression within the parent OR or
+            // AND into an OR with the necessary EXISTS condition. Splitting each filter into an OR
+            // could result in a much larger AST than necessary and slow down Schema Matching.
```
Comment (kirkrodrigues) [inline components/core/src/clp_s/search/NarrowTypes.cpp:118]:
```suggestion
            // on the same column (as is common when someone tries to filter out, e.g., a long list
            // of UUIDs) then we only need to transform one filter expression within the parent
            // OR/AND into an OR with the necessary EXISTS condition. Splitting each filter into an
            // OR could result in a much larger AST than necessary and slow down Schema Matching.
```

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]
Minor writing comments.

**Review by wraymo — APPROVED** [review]

**Review by kirkrodrigues — APPROVED** [review]
Commit msg: `clp-s: Handle multiple string types when narrowing types in an != filter (fixes #254).`?
