### PR TITLE
fix(core): Replace unsigned integer literals with `size_t` casts for type safety (fixes #1879).

### LINKED ISSUE #1879: Narrowing conversion errors when compiling TimestampParser.cpp for 32-bit WebAssembly
### Bug

`components/core/src/clp_s/timestamp_parser/TimestampParser.cpp` uses `1ULL` and `0ULL` literals in ternary expressions assigned to `size_t` variables. This causes narrowing conversion errors when compiling for 32-bit platforms (e.g., WebAssembly where `size_t` is 32-bit).

The affected lines use `unsigned long long` literals for values that are indices/sizes and don't need 64-bit precision:

https://github.com/y-scope/clp/blob/59fe7adb0d62edc4ca079065e66a4a4f90adafcb/components/core/src/clp_s/timestamp_parser/TimestampParser.cpp#L399
https://github.com/y-scope/clp/blob/59fe7adb0d62edc4ca079065e66a4a4f90adafcb/components/core/src/clp_s/timestamp_parser/TimestampParser.cpp#L916
https://github.com/y-scope/clp/blob/59fe7adb0d62edc4ca079065e66a4a4f90adafcb/components/core/src/clp_s/timestamp_parser/TimestampParser.cpp#L917
https://github.com/y-scope/clp/blob/59fe7adb0d62edc4ca079065e66a4a4f90adafcb/components/core/src/clp_s/timestamp_parser/TimestampParser.cpp#L1187
https://github.com/y-scope/clp/blob/59fe7adb0d62edc4ca079065e66a4a4f90adafcb/components/core/src/clp_s/timestamp_parser/TimestampParser.cpp#L1188

**Expected:** Code should compile without warnings on both 32-bit and 64-bit platforms.

**Suggested fix:** Replace `1ULL`/`0ULL` with explicit `size_t` casts:
```cpp
size_t num_decimal_digits{is_negative ? size_t{1} : size_t{0}};
```

### CLP version

491e321fd7e7e2127c211ebb6719186e06c63349

### Environment

- Emscripten 4.0.10 (WebAssembly, 32-bit `size_t`)
- Ubuntu 22.04

### Reproduction steps

1. Set up Emscripten toolchain
2. Configure CMake with Emscripten toolchain file
3. Build `clp_s_timestamp_parser` target
4. Observe compilation errors:
   ```
   error: non-constant-expression cannot be narrowed from type 'unsigned long long' to 'size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
   ```

### PR DESCRIPTION
**Pull request by junhaoliao**
# Description

Replaces unsigned integer literals (0ULL, 1ULL, etc.) with explicit size_t casts.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

Ensured all linter checks passed.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

* **Refactor**
  * Standardized numeric literal types across core parsing and formatting components, replacing unsigned literal suffixes with explicit size_t initializations to improve type safety, consistency and maintainability without changing runtime behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1212876404111288
  - https://app.asana.com/0/0/1212876407852903
  - https://app.asana.com/0/0/1212888453872236
  - https://app.asana.com/0/0/1212854499666590

### CODE REVIEW

File: components/core/src/clp_s/FloatFormatEncoding.cpp [hunk 1]
```diff
@@ -75,7 +75,9 @@ auto trim_leading_zeros(std::string_view scientific_notation, size_t start, size
         return sci_str;
     }
     size_t actual_number_of_zeros_to_trim{0};
-    auto const limit{num_exp_digits > sci_str.length() ? 0ULL : sci_str.length() - num_exp_digits};
+    auto const limit{
+            num_exp_digits > sci_str.length() ? size_t{0} : sci_str.length() - num_exp_digits
```
Comment (gibber9809) [inline components/core/src/clp_s/FloatFormatEncoding.cpp]:
```suggestion
            num_exp_digits > sci_str.length() ? size_t{0} : (sci_str.length() - num_exp_digits)
```
Since we're updating this anyway, I have a bit of a preference for explicit brackets

File: components/core/src/clp_s/timestamp_parser/TimestampParser.cpp [hunk 2]
```diff
@@ -913,8 +914,8 @@ auto TimestampPattern::create(std::string_view pattern)
     bool const is_quoted_pattern{
             pattern.size() >= 2 && '"' == pattern.front() && '"' == pattern.back()
     };
-    size_t const start_idx{is_quoted_pattern ? 1ULL : 0ULL};
-    size_t const end_idx{is_quoted_pattern ? pattern.size() - 1ULL : pattern.size()};
+    size_t const start_idx{is_quoted_pattern ? size_t{1} : size_t{0}};
+    size_t const end_idx{is_quoted_pattern ? pattern.size() - 1 : pattern.size()};
```
Comment (gibber9809) [inline components/core/src/clp_s/timestamp_parser/TimestampParser.cpp]:
```suggestion
    size_t const end_idx{is_quoted_pattern ? (pattern.size() - 1) : pattern.size()};
```

**Review by gibber9809 — CHANGES_REQUESTED** [review]
Looks good! Just some minor nits for code that's part of this diff anyway.
