### PR TITLE
Consolidate parsing methods from ffi and non-ffi code (fixes #160)

### LINKED ISSUE #160: Searching for a variable with a '/' in an archive composed of IR files returns nothing
### Bug

If we compress an IR file containing a variable with one or more forward slashes (e.g., "/usr/bin/python3") into archive and then try to search for that variable using `clg` (e.g., `./clg archives "/usr/bin/python3"`), the search returns nothing.

### CLP version

084efa3

### Environment

Ubuntu 20.04

### Reproduction steps

* Create an IR file (using the four-byte encoding) containing a log message: `2023-09-16T00:00:00.000 INFO Python's path is /usr/bin/python3?`
* Compress that IR file using clp: `./clp c archives test.clp.zst`
* Search for the path string: `./clg archives "/usr/bin/python3"`

### PR DESCRIPTION
**Pull request by kirkrodrigues**
# References

#160

# Description

The parsing methods in `ffi` and those outside were using different delimiters leading which caused #160. This PR finally consolidates the parsing methods from the two into the `ir` namespace.

# Validation performed

* Validated #160 was fixed by following its reproduction steps
* Ran unit tests
* Validated compression & decompression are lossless
* Validated basic search queries

### CODE REVIEW

File: components/core/src/ffi/ir_stream/encoding_methods.cpp [hunk 1]
```diff
@@ -177,30 +165,11 @@ static void add_base_metadata_fields(
...
-        if (cVariablePlaceholderEscapeCharacter == c || is_variable_placeholder(c)) {
-            logtype.append(constant, begin_pos, i - begin_pos);
-            logtype += cVariablePlaceholderEscapeCharacter;
-            // NOTE: We don't need to append the character of interest
-            // immediately since the next constant copy operation will get it
-            begin_pos = i;
-        }
-    }
-    logtype.append(constant, begin_pos, constant_len - begin_pos);
+static bool append_constant_to_logtype(string_view constant, string& logtype) {
```
Comment (LinZhihao-723) [inline components/core/src/ffi/ir_stream/encoding_methods.cpp:168]: Not a problem of this PR, but we should use empty namespace instead of `static` to be consistent

File: components/core/src/ir/parsing.cpp [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+
+using std::string_view;
+
+namespace ir {
+/*
+ * For performance, we rely on the ASCII ordering of characters to compare
+ * ranges of characters at a time instead of comparing individual characters
+ */
+bool is_delim(signed char c) {
+    return !(
```
Comment (LinZhihao-723) [inline components/core/src/ir/parsing.cpp:14]:
```suggestion
    return false == (
```

File: components/core/src/ir/parsing.cpp [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+        // Ensure the entire value is a variable
+        return (0 == begin_pos && value.length() == end_pos);
+    } else {
+        return false;
+    }
+}
+
+bool get_bounds_of_next_var(string_view const str, size_t& begin_pos, size_t& end_pos) {
+    auto const msg_length = str.length();
+    if (end_pos >= msg_length) {
```
Comment (LinZhihao-723) [inline components/core/src/ir/parsing.cpp:39]: Const on the left
```suggestion
    if (msg_length <= end_pos) {
```

File: components/core/src/ir/parsing.cpp [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+            }
+        }
+
+        auto variable = str.substr(begin_pos, end_pos - begin_pos);
+        // Treat token as variable if:
+        // - it contains a decimal digit, or
+        // - it's directly preceded by '=' and contains an alphabet char, or
+        // - it could be a multi-digit hex value
+        if (contains_decimal_digit
+            || (begin_pos > 0 && '=' == str[begin_pos - 1] && contains_alphabet)
```
Comment (LinZhihao-723) [inline components/core/src/ir/parsing.cpp:80]:
```suggestion
            || (0 < begin_pos && '=' == str[begin_pos - 1] && contains_alphabet)
```

File: components/core/src/ir/parsing.hpp [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+ */
+inline bool could_be_multi_digit_hex_value(std::string_view str) {
+    if (str.length() < 2) {
+        return false;
+    }
+
+    // NOTE: This is 1-2% faster than using std::all_of with the opposite
+    // condition
+    for (auto c : str) {
+        if (!(('a' <= c && c <= 'f') || ('A' <= c && c <= 'F') || ('0' <= c && c <= '9'))) {
```
Comment (LinZhihao-723) [inline components/core/src/ir/parsing.hpp:52]:
```suggestion
        if (false == (('a' <= c && c <= 'f') || ('A' <= c && c <= 'F') || ('0' <= c && c <= '9'))) {
```

File: components/core/src/LogTypeDictionaryEntry.cpp [hunk 6]
```diff
@@ -133,18 +107,18 @@ ErrorCode LogTypeDictionaryEntry::try_read_from_file (streaming_compression::Dec
...
                 constant.clear();
                 add_int_var();
-            } else if (enum_to_underlying_type(LogTypeDictionaryEntry::VarDelim::Float) == c) {
+            } else if (enum_to_underlying_type(ir::VariablePlaceholder::Float) == c) {
                 add_constant(constant, 0, constant.length());
                 constant.clear();
                 add_float_var();
-            } else if (enum_to_underlying_type(LogTypeDictionaryEntry::VarDelim::Dictionary) == c)
+            } else if (enum_to_underlying_type(ir::VariablePlaceholder::Dictionary) == c)
             {
```
Comment (LinZhihao-723) [inline components/core/src/LogTypeDictionaryEntry.cpp:122]:
```suggestion
            } else if (enum_to_underlying_type(ir::VariablePlaceholder::Dictionary) == c) {
```

**Review by LinZhihao-723 — CHANGES_REQUESTED** [review]
Add a few comments

File: components/core/src/ffi/ir_stream/encoding_methods.cpp (hunk 1 above)
Comment (kirkrodrigues) [reply components/core/src/ffi/ir_stream/encoding_methods.cpp:168]: Yeah, we'll resolve these when we apply clang-tidy suggestions to the codebase.

**Review by LinZhihao-723 — APPROVED** [review]
