### PR TITLE
webui: Unquote clp queries before submitting them to the backend (fixes #344).

### LINKED ISSUE #344: Quoting (") the query in the webui searches *with* the quotes rather than stripping them.
### Bug

Searching for `" info "` in the webui searches for the literal string `" info "`, including the quotes, meaning that the query doesn't find matches for ` info `. User expectation is that the quotes would be stripped unless escaped.

### CLP version

ce3af8d

### Environment

Ubuntu 20.04

### Reproduction steps

* Build a package

  ```shell
  task package
  ```

* Start the package

  ```shell
  cd build/clp-package
  sbin/start-clp.sh
  ```

* Compress https://zenodo.org/records/7094921

  ```shell
  sbin/compress.sh hive-24hr
  ```

* Open the webui (http://localhost:4000/search)
* Enter the query ` INFO ` in the webui and observe results are returned
* Enter the query `" INFO "` in the webui and observe *no* results are returned

### PR DESCRIPTION
**Pull request by kirkrodrigues**
# References

#344

# Description

Users of clp (the "clp" storage engine in the CLP package) expect to be able to quote their queries so that delimiters like spaces are more obvious when sent to the backend. This PR adds support for that.

The specific quoting behaviour is as follows:

* Users can either enter their query without quotes, or with double-quotes (") wrapping both ends of the query.
* Double-quotes within the query must be escaped with the '\' escape character.
* Non-double-quotes that are escaped are preserved, e.g., wildcards and notably, escapes.
  * This non-standard behaviour is so that users don't need to insert *extra* escapes just to pass escaped wildcards to clp.

# Validation performed

* Validated new unit tests pass.
* Validated queries against a clp package:
  * Compressed the [hive-24hr](https://zenodo.org/records/7094921) dataset
    ```shell
    sbin/compress.sh hive-24hr
    ```
  * Tested the following queries from the webui:
    * ` info ` was sent to the backend verbatim
    * `" info "` was sent as ` info `
    * `"\"mapreduce_shuffle\""` was sent as `"mapreduce_shuffle"`
    * `BLOCK\*` was sent as `BLOCK\*`
    * `"BLOCK\*"` was sent as `BLOCK\*`
    * `\\` was sent as `\\`
    * `"\\"` was sent as `\\`
* Validated queries against clp-s are passed verbatim to the backend.

### CODE REVIEW

File: components/webui/imports/ui/SearchView/SearchView.jsx [hunk 1]
```diff
@@ -144,6 +146,21 @@ const SearchView = () => {
...
         }
 
+        let processedQueryString;
+        if (CLP_STORAGE_ENGINES.CLP_S === Meteor.settings.public.ClpStorageEngine) {
+            processedQueryString = queryString;
+        } else {
+            try {
+                processedQueryString = unquoteString(queryString, '"', '\\');
+                if ("" === processedQueryString) {
+                    throw new Error("Cannot be empty.");
```
Comment (junhaoliao) [inline components/webui/imports/ui/SearchView/SearchView.jsx:156]: We're `throw`ing the exception here because supposedly the UI does not permit any submission when the text field is empty, right?

File: components/webui/tests/misc.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
+import assert from "assert";
+
+import {unquoteString} from "/imports/utils/misc";
+
+describe("misc", function () {
+    it("unquoteString", function () {
+        // Unquoted string
```
Comment (junhaoliao) [inline components/webui/tests/misc.js:7]: It will be good to ensure 100% test coverage of the function.
```suggestion
        // Empty string
        assert.strictEqual(unquoteString("", "\"", "\\"), "");
        // Unquoted string
```

File: components/webui/imports/utils/misc.js [hunk 3]
```diff
@@ -23,4 +23,68 @@ const computeHumanSize = (num) => {
...
+ * unescaping quotes.
+ * @param str
+ * @param quoteChar
+ * @param escapeChar
+ * @return The processed string
+ * @throws Error if the quoted string has a quote within it (rather than at its ends) or it's
+ * missing one of it's begin/end quotes.
+ */
+function unquoteString(str, quoteChar, escapeChar) {
+    if (str.length === 0) {
```
Comment (junhaoliao) [inline components/webui/imports/utils/misc.js:39]:
```suggestion
    if (0 === str.length) {
```

File: components/webui/imports/utils/misc.js [hunk 4]
```diff
@@ -23,4 +23,68 @@ const computeHumanSize = (num) => {
...
+        if (quoteChar === char) {
+            if (0 === pos) {
+                foundBeginQuote = true;
+            } else if (chars.length - 1 === pos) {
+                foundEndQuote = true;
+            } else {
+                throw new Error(`Found unescaped quote character (${quoteChar}) within.`);
+            }
+        }
+    }
```
Comment (junhaoliao) [inline components/webui/imports/utils/misc.js:81]:
```suggestion
    positionOfCharsToRemove.forEach((pos) => {
        const char = chars[pos];
        if (quoteChar === char) {
            if (0 === pos) {
                foundBeginQuote = true;
            } else if (chars.length - 1 === pos) {
                foundEndQuote = true;
            } else {
                throw new Error(`Found unescaped quote character (${quoteChar}) within.`);
            }
        }
    });
```

File: components/webui/imports/utils/misc.js [hunk 5]
```diff
@@ -23,4 +23,68 @@ const computeHumanSize = (num) => {
...
+ * NOTE: This method does *not* unescape non-quote characters, unlike most methods which handle
+ * unescaping quotes.
+ * @param str
+ * @param quoteChar
+ * @param escapeChar
+ * @return The processed string
+ * @throws Error if the quoted string has a quote within it (rather than at its ends) or it's
+ * missing one of it's begin/end quotes.
+ */
+function unquoteString(str, quoteChar, escapeChar) {
```
Comment (junhaoliao) [inline components/webui/imports/utils/misc.js:38]:
```suggestion
const unquoteString = (str, quoteChar, escapeChar) => {
```

File: components/webui/imports/ui/SearchView/SearchView.jsx [hunk 6]
```diff
@@ -144,6 +146,21 @@ const SearchView = () => {
             handleClearResults();
         }
 
+        let processedQueryString;
+        if (CLP_STORAGE_ENGINES.CLP_S === Meteor.settings.public.ClpStorageEngine) {
+            processedQueryString = queryString;
+        } else {
```
Comment (junhaoliao) [inline components/webui/imports/ui/SearchView/SearchView.jsx:152]:
```suggestion
        let processedQueryString = queryString;
        if (CLP_STORAGE_ENGINES.CLP === Meteor.settings.public.ClpStorageEngine) {
```

**Review by junhaoliao — CHANGES_REQUESTED** [review]
Looks good to me. Some minor refactoring suggestions.

File: components/webui/imports/ui/SearchView/SearchView.jsx (hunk 1 above)
Comment (kirkrodrigues) [reply components/webui/imports/ui/SearchView/SearchView.jsx:156]: The backend doesn't support empty query strings. In the UI, the user can't submit an empty string as their query since the form won't let them. However, the form does let them submit an empty quoted string, so this check is to handle that.

File: components/webui/imports/utils/misc.js [hunk 7]
```diff
@@ -23,4 +23,67 @@ const computeHumanSize = (num) => {
...
+ * @param escapeChar
+ * @return The processed string
+ * @throws Error if the quoted string has a quote within it (rather than at its ends) or it's
+ * missing one of it's begin/end quotes.
+ */
+const unquoteString = (str, quoteChar, escapeChar) => {
+    if (0 === str.length) {
+        return str;
+    }
+
```
Comment (junhaoliao) [inline components/webui/imports/utils/misc.js:42]:
```suggestion
```

File: components/webui/imports/utils/misc.js [hunk 8]
```diff
@@ -23,4 +23,67 @@ const computeHumanSize = (num) => {
...
+            isEscaped = true;
+        } else if (c === quoteChar) {
+            positionOfCharsToRemove.push(i);
+        }
+    }
+
+    if (positionOfCharsToRemove.length === 0) {
+        return str;
+    }
+
```
Comment (junhaoliao) [inline components/webui/imports/utils/misc.js:65]:
```suggestion
```

File: components/webui/imports/utils/misc.js [hunk 9]
```diff
@@ -23,4 +23,67 @@ const computeHumanSize = (num) => {
...
+                throw new Error(`Found unescaped quote character (${quoteChar}) within.`);
+            }
+        }
+    });
+    if (foundBeginQuote ^ foundEndQuote) {
+        throw new Error("Begin/end quote is missing.");
+    }
+
+    const processedChars = chars.filter((c, i) => false === positionOfCharsToRemove.includes(i));
+    return processedChars.join("");
```
Comment (junhaoliao) [inline components/webui/imports/utils/misc.js:86]:
```suggestion
    const result = processedChars.join("");

    if (0 === result.length) {
        throw new Error("Cannot be empty.");
    }

    return result;
```

File: components/webui/tests/misc.js [hunk 10]
```diff
@@ -0,0 +1,36 @@
+import assert from "assert";
+
+import {unquoteString} from "/imports/utils/misc";
+
+describe("misc", function () {
+    it("unquoteString", function () {
+        // Empty string
+        assert.strictEqual(unquoteString("", '"', '\\'), "");
```
Comment (junhaoliao) [inline components/webui/tests/misc.js:8]:
```suggestion
```

File: components/webui/tests/misc.js [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+        assert.strictEqual(unquoteString("abc", '"', '\\'), "abc");
+        // Double-quoted string
+        assert.strictEqual(unquoteString("\"abc\"", '"', '\\'), "abc");
+        // Single-quoted string
+        assert.strictEqual(unquoteString("'abc'", "'", '\\'), "abc");
+        // With escaped characters
+        assert.strictEqual(unquoteString("a\\\\b\\\"c\\*\\?", '"', '\\'), "a\\\\b\"c\\*\\?");
+        // Double-quoted with escaped characters
+        assert.strictEqual(unquoteString("\"a\\\\b\\\"c\\*\\?\"", '"', '\\'), "a\\\\b\"c\\*\\?");
+
```
Comment (junhaoliao) [inline components/webui/tests/misc.js:19]:
```suggestion

// Empty string
assert.throws(() => {
    unquoteString("", '"', '\\');
}, Error);
assert.throws(() => {
    unquoteString('""', '"', '\\');
}, Error);

```

File: components/webui/imports/utils/misc.js [hunk 12]
```diff
@@ -23,4 +23,67 @@ const computeHumanSize = (num) => {
...
+ * Removes wrapping quotes from the given string, if it's quoted, and unescapes quotes from within
+ * the quoted string.
+ * NOTE: This method does *not* unescape non-quote characters, unlike most methods which handle
+ * unescaping quotes.
+ * @param str
+ * @param quoteChar
+ * @param escapeChar
+ * @return The processed string
+ * @throws Error if the quoted string has a quote within it (rather than at its ends) or it's
+ * missing one of it's begin/end quotes.
```
Comment (junhaoliao) [inline components/webui/imports/utils/misc.js:36]:
```suggestion
 * @throws Error if any:
 *      - the quoted string has a quote within it (rather than at its ends)
 *      - it's missing one of it's begin/end quotes
 *      - the quoted / processed string is an empty one
```

File: components/webui/imports/ui/SearchView/SearchView.jsx (hunk 1 above)
Comment (junhaoliao) [reply components/webui/imports/ui/SearchView/SearchView.jsx:154]: Gotcha. 

Would it be better to throw directly in `unquoteString` so that we can avoid `throw`ing in a `try-catch` here?

**Review by junhaoliao — COMMENTED** [review]
We can move the empty-string exception throw into `unquoteString`.

**Comment by haiqi96** [comment]
looks good to me. I don't have any specific concern

**Comment by junhaoliao** [comment]
> We can move the empty-string exception throw into `unquoteString`.

Another thought - generally it is not wrong to have an empty quoted/unquoted string unless we rename/repurpose the function otherwise. Maybe we just need to avoid throwing in a catch.

**Comment by kirkrodrigues** [comment]
> Another thought - generally it is not wrong to have an empty quoted/unquoted string unless we rename/repurpose the function otherwise. Maybe we just need to avoid throwing in a catch.

Yeah, that was my original thought. I'm throwing in the catch just so we can avoid the call again to `setOperationErrorMsg`, but not a big deal to repeat it.

**Comment by junhaoliao** [comment]
> > Another thought - generally it is not wrong to have an empty quoted/unquoted string unless we rename/repurpose the function otherwise. Maybe we just need to avoid throwing in a catch.
> 
> Yeah, that was my original thought. I'm throwing in the catch just so we can avoid the call again to `setOperationErrorMsg`, but not a big deal to repeat it.

Gotcha. I agree with the current handling then.

**Review by junhaoliao — APPROVED** [review]
Looks good to me and I agree with the PR title.

**Review by junhaoliao — APPROVED** [review]
