### PR TITLE
fix(core-clp): Advance to the next message when a message has an out-of-range timestamp when searching archives (fixes #659).

### LINKED ISSUE #659: Search query locked up when a non-full time range is specified.
### Bug

It was observed that when a search query is submitted in the Web UI with a non-full time range, the search query will be in pending status indefinitely. The issue is not observed with the default "All Time" time range.

By method of exclusion, it is believed that this is the violating change 24f5fdf7ecd056ea4fb8d82afbf52bac1267a037: https://github.com/y-scope/clp/pull/426

### CLP version

5d3b67145876d90defa45aeab0a37e9ad48aaddf

### Environment

Ubuntu Jammy WSL
Microsoft Edge: Version 131.0.2903.112 (Official build) (64-bit)

### Reproduction steps

1. Clone the repo.
2. `git checkout 24f5fdf7ecd056ea4fb8d82afbf52bac1267a037`
3. `task` to build the package.
4. `cd build/clp-package/sbin`
5. `./start-clp.sh`
6. `./compress.sh ~/sample/hive-24hr`
7. Launch the Web UI's search panel http://localhost:4000/search in a browser.
8. Query with `1` and observe the query completes successfully.
9. Use the timeline to change the time range to a narrower one like Year 2008 - Year 2015. As a result, a query is started with the narrower time range. Observe that the query keeps running with a pending status.
10. Check the job orchestration db and find that the job has a PENDING `status`.

### PR DESCRIPTION
**Pull request by LinZhihao-723**
# Description

#426 introduced a refactoring for querying messages in archive files. This refactoring has a bug that doesn't increment the message index when the message's timestamp is out of the query's timestamp range.
This PR fixes the issue by incrementing the message indices before any loop branching that could lead to the next loop iteration.

# Validation performed

- Ensure all workflows passed.
- Ensure the bug has been fixed, confirmed with @junhaoliao 

## Summary by CodeRabbit

- **Refactor**
	- Improved index management in message search functionality.
	- Enhanced tracking of message and variable indices.
	- Clarified index advancement logic in search method.

These changes enhance the clarity and correctness of the message search process, ensuring a more straightforward experience for users without altering the external interface.

### CODE REVIEW

**Review by junhaoliao — DISMISSED** [review]
I validated the changes in the WebUI with steps specified in https://github.com/y-scope/clp/issues/659 and the issue is now no longer observed.

I understand the source of the bug, and the changes look right to me, but someone with more experience with the CLP core code should also take a look.

File: components/core/src/clp/streaming_archive/reader/File.cpp [hunk 1]
```diff
@@ -252,14 +252,20 @@ bool File::find_message_in_time_range(
...
     while (m_msgs_ix < m_num_messages && nullptr == matching_sub_query) {
-        auto logtype_id = m_logtypes[m_msgs_ix];
+        auto const curr_msg_ix{m_msgs_ix};
+        auto logtype_id = m_logtypes[curr_msg_ix];
 
         // Get number of variables in logtype
         auto const& logtype_dictionary_entry = m_archive_logtype_dict->get_entry(logtype_id);
         auto const num_vars = logtype_dictionary_entry.get_num_variables();
-
+        auto const var_begin_ix{m_variables_ix};
```
Comment (kirkrodrigues) [inline components/core/src/clp/streaming_archive/reader/File.cpp:261]: `vars_begin_ix` to be consistent

Comment (kirkrodrigues) [inline components/core/src/clp/streaming_archive/reader/File.cpp:261]:
```suggestion

        auto const var_begin_ix{m_variables_ix};
```

The comment above is not related to these two lines, so I think it's worth breaking up the two blocks.

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

**Review by kirkrodrigues — APPROVED** [review]
For the PR title, how about:

```
fix(core-clp): Advance to the next message when a message has an out-of-range timestamp when searching archives (fixes #659).
```
