### PR TITLE
fix(new-webui): Drop timezone from `Date`s returned by antd's `DatePicker.RangePicker` to match timezone (UTC) shown in search results (fixes #1085).

### LINKED ISSUE #1085: [new-webui] Time range selected via selector is offset from time range sent in query
### Bug

Time ranges selected via the selector are offset from the timezone shown, resulting in the wrong time range filter in the query.

### CLP version

f1979be993c1b0d166670576ee2e24e5d6cfcf87

### Environment

Firefox 140.0.2 (64-bit)

### Reproduction steps

* Start the package
* Compress a dataset
* Perform a search in the UI
* Select a custom time range
* Send the query
* Open the console
* Observe that the time range sent with the query is offset from the time range selected

### PR DESCRIPTION
**Pull request by davemarco**
# Description

@kirkrodrigues mentioned a bug that the range picker is not accurately selecting dates. 

PR fixes this issue by dropping any timezone offset supplied by antd range picker.

PR also drops `showNow` options since it selects the time in the local timezone. This does not work for our design since the whole in UI is in utc.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

tested the submitted timestamp in utc is the same when (1) using the selector, and (2) when clearing the timestamp first then using the selector.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

* **Bug Fixes**
  * Updated the date range picker in the custom time range selection to prevent clearing the selection and hide the "now" button, ensuring consistent timezone handling.

### CODE REVIEW

**Comment by kirkrodrigues** [comment]
> however, the "allowClear" and "now" options reset the timezone to the local timezone.

How'd you figure that out?

File: components/webui/client/src/pages/SearchPage/SearchControls/TimeRangeInput/index.tsx [hunk 1]
```diff
@@ -68,8 +68,12 @@ const TimeRangeInput = () => {
                 onChange={handleSelectChange}/>
             {timeRangeOption === TIME_RANGE_OPTION.CUSTOM && (
                 <DatePicker.RangePicker
+
+                    // `ShowNow` and `allowClear` options are disabled since they set the timezone
+                    //  of the range picker to the local timezone.
```
Comment (kirkrodrigues) [inline components/webui/client/src/pages/SearchPage/SearchControls/TimeRangeInput/index.tsx]:
```suggestion
                    // NOTE: We disable `showNow` and `allowClear` since they set the timezone of
                    // the range picker to the local timezone.
```

**Comment by davemarco** [comment]
> > however, the "allowClear" and "now" options reset the timezone to the local timezone.
> 
> How'd you figure that out?

I tested. If you look at logs from the UI in the console. You will see that the submitted timestamp is 4 hours off (after you clear it). The now option was also using my local time, and not the utc time.

**Comment by kirkrodrigues** [comment]
Entering a timestamp by typing also seems to trigger the issue. Any ideas how we could fix/mitigate that as well?

**Comment by davemarco** [comment]
> Entering a timestamp by typing also seems to trigger the issue. Any ideas how we could fix/mitigate that as well?

This is kind of annoying. Maybe we do a gross [manipulation](https://day.js.org/docs/en/manipulate/utc)  (i think the timeline does something like this) when updating the state ? I think you can use `utc(true)` and it will drop the existing offset. The manipulation should have no effect if already in utc, and if not, it will force it to utc?

It dosent seem antd provides good support for timezones.

Originally i wanted to avoid this, and I thought setting the starting timestamp in utc was elegant fix, but it turns out it dosent work. 

we will still have to drop "now" feature since it will be local time, but allow clear should be fine

**Comment by kirkrodrigues** [comment]
> Maybe we just keep the selector in the local timezone, and due a gross [manipulation](https://day.js.org/docs/en/manipulate/utc) when submitting the query (i think the timeline does something like this)? I think you can use `utc(true)` and it will drop the existing offset. It dosent seem antd provides good support for timezones

Sounds reasonable for now.

**Comment by davemarco** [comment]
@kirkrodrigues - i made the fix. It appears to work, overall it is not that messy.

File: components/webui/client/src/pages/SearchPage/SearchControls/TimeRangeInput/index.tsx [hunk 2]
```diff
@@ -68,8 +72,9 @@ const TimeRangeInput = () => {
                 onChange={handleSelectChange}/>
             {timeRangeOption === TIME_RANGE_OPTION.CUSTOM && (
                 <DatePicker.RangePicker
+
```
Comment (kirkrodrigues) [inline components/webui/client/src/pages/SearchPage/SearchControls/TimeRangeInput/index.tsx]:
```suggestion
```

**Review by kirkrodrigues — COMMENTED** [review]
Could you update the PR description about why we removed `showNow` as well as the updated validation steps?

**Review by kirkrodrigues — APPROVED** [review]
For the PR title, how about:

```
fix(new-webui): Drop timezone from `Date`s returned by antd's `DatePicker.RangePicker` to match timezone (UTC) shown in search results.
```
