### PR TITLE
core: Add support for retrieving CURL error messages, handle unexpected CURL return code on macOS, and log such codes in tests (fixes #519).

### LINKED ISSUE #519: `network_reader_illegal_offset` unit test failure on macOS
### Bug

The `network_reader_illegal_offset` unit test is failing on GH's macOS runners. The issue is being investigated and mitigated in #517.

### CLP version

1b67fdb

### Environment

Any macOS GH runner

### Reproduction steps

Run the clp-core-build-macos workflow on a macOS GH runner.

### PR DESCRIPTION
**Pull request by LinZhihao-723**
# Description

This PR fixes #519.
In recent workflows, we found that some macOS build failed because of the unit test failures. By further investigation, it is because HTTP error code 416 is not handled as `CURL_HTTP_RETURNED_ERROR` in the `libcurl` version of the GH macOS runner. The same issue won't be reproduced in ubuntu 20.04 or 22.04 even with the same version of `libcurl`. Therefore, this PR adds special handling for macOS to address the failure in the unit test cases.
In addition, as we were approaching the cause of the failure, we realized the CURL error message could be helpful. Therefore, we also add support for retrieving CURL error messages through the `CurlDownloadHandler` to improve the debugability of our CURL utilities. In the unit test, we add logs to print out the error messages when the CURL return code doesn't match the expected one.

# Validation performed

- Ensure workflow can be successfully built except on centOS, which is tracked by #521 and is not related to this PR.
- Unit tests all passed.

### CODE REVIEW

File: components/core/tests/test-NetworkReader.cpp [hunk 1]
```diff
@@ -35,6 +35,14 @@ constexpr size_t cDefaultReaderBufferSize{1024};
 auto get_content(clp::ReaderInterface& reader, size_t read_buf_size = cDefaultReaderBufferSize)
         -> std::vector<char>;
 
+/**
+ * Asserts whether the given two `CURLcode` are the same. On failure, it will aborts the execution
+ * of the current test and logs the error code.
+ * @parma expected
```
Comment (kirkrodrigues) [inline components/core/tests/test-NetworkReader.cpp:41]:
```suggestion
 * Asserts whether the given two `CURLcode` are the same. On failure, it aborts execution of the
 * current test and logs the mismatched error codes.
 * @param expected
```

File: components/core/tests/test-NetworkReader.cpp [hunk 2]
```diff
@@ -64,6 +72,17 @@ auto get_content(clp::ReaderInterface& reader, size_t read_buf_size) -> std::vec
...
+
+auto assert_curl_error_code(CURLcode expected, CURLcode actual) -> void {
+    if (expected == actual) {
+        return;
+    }
+    std::string const error_message{
+            "Unexpected CURL error code: " + std::to_string(actual)
+            + "; expected: " + std::to_string(expected)
+    };
+    FAIL(error_message);
```
Comment (kirkrodrigues) [inline components/core/tests/test-NetworkReader.cpp:84]: Based on https://curl.se/libcurl/c/libcurl-errors.html, can we also use [CURLOPT_ERRORBUFFER](https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html) so that we can get more details about the error (e.g., what specific HTTP error >= 400 it was)?

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

File: components/core/tests/test-NetworkReader.cpp [hunk 3]
```diff
@@ -35,6 +43,16 @@ constexpr size_t cDefaultReaderBufferSize{1024};
 auto get_content(clp::ReaderInterface& reader, size_t read_buf_size = cDefaultReaderBufferSize)
         -> std::vector<char>;
 
+/**
+ * Asserts whether the given `CURLcode` and the return code stored in the given `NetworkReader`
+ * instance are the same. A log message will be printed when the assertion fails.
```
Comment (kirkrodrigues) [inline components/core/tests/test-NetworkReader.cpp:48]:
```suggestion
 * Asserts whether the given `CURLcode` and the CURL return code stored in the given `NetworkReader`
 * instance are the same, and prints a log message if not.
```

File: components/core/tests/test-NetworkReader.cpp [hunk 4]
```diff
@@ -64,6 +82,28 @@ auto get_content(clp::ReaderInterface& reader, size_t read_buf_size) -> std::vec
     }
     return buf;
 }
+
+auto assert_curl_error_code(CURLcode expected, clp::NetworkReader const& reader) -> bool {
+    auto const ret_code{reader.get_curl_ret_code()};
+    if (false == ret_code.has_value()) {
+        WARN("The CURL error code hasn't been received yet in the given reader.");
```
Comment (kirkrodrigues) [inline components/core/tests/test-NetworkReader.cpp:89]:
```suggestion
        WARN("The CURL error code hasn't been set yet in the given reader.");
```

File: components/core/tests/test-NetworkReader.cpp [hunk 5]
```diff
@@ -147,13 +178,20 @@ TEST_CASE("network_reader_illegal_offset", "[NetworkReader]") {
...
-            size_t pos{};
-            REQUIRE((clp::ErrorCode_Failure == reader.try_get_pos(pos)));
-            break;
-        }
+    while (false == reader.get_curl_ret_code().has_value()) {
+        // Wait until the return code is ready
+    }
+
+    if constexpr (cIsMacOS) {
+        // On macOS, HTTP return code 416 is not handled as `CURL_HTTP_RETURNED_ERROR` in some
```
Comment (kirkrodrigues) [inline components/core/tests/test-NetworkReader.cpp:186]:
```suggestion
        // On macOS, HTTP response code 416 is not handled as `CURL_HTTP_RETURNED_ERROR` in some
```

File: components/core/src/clp/NetworkReader.hpp [hunk 6]
```diff
@@ -216,6 +216,20 @@ class NetworkReader : public ReaderInterface {
         return m_curl_ret_code.load();
     }
 
+    /**
+     * @return The error message set by the underlying CURL handler.
+     * @return std::nullopt if the download is still in-progress, or a success error code is
+     * returned.
```
Comment (kirkrodrigues) [inline components/core/src/clp/NetworkReader.hpp:222]:
```suggestion
     * @return std::nullopt if the download is still in-progress or no error has occured.
```

File: components/core/src/clp/NetworkReader.cpp [hunk 7]
```diff
@@ -158,6 +158,13 @@ auto NetworkReader::try_get_pos(size_t& pos) -> ErrorCode {
                 // offset specified in the HTTP header.
                 return ErrorCode_Failure;
             }
+#if defined(__APPLE__)
```
Comment (kirkrodrigues) [inline components/core/src/clp/NetworkReader.cpp:161]: Can we use `cCurrentPlatform` from `Platform.hpp`?

File: components/core/src/clp/NetworkReader.cpp [hunk 8]
```diff
@@ -158,6 +158,13 @@ auto NetworkReader::try_get_pos(size_t& pos) -> ErrorCode {
...
+            if (CURLE_RECV_ERROR == curl_return_code.value()) {
+                // On macOS, HTTP return code 416 is not handled as `CURL_HTTP_RETURNED_ERROR` in
+                // some `libcurl` versions.
```
Comment (kirkrodrigues) [inline components/core/src/clp/NetworkReader.cpp:164]:
```suggestion
            // On macOS, HTTP response code 416 is not handled as `CURL_HTTP_RETURNED_ERROR` in
            // some `libcurl` versions.
            if (CURLE_RECV_ERROR == curl_return_code.value()) {
```

File: components/core/src/clp/CurlDownloadHandler.hpp [hunk 9]
```diff
@@ -28,6 +31,7 @@ class CurlDownloadHandler {
      * https://curl.se/libcurl/c/CURLOPT_WRITEFUNCTION.html
      */
     using WriteCallback = size_t (*)(char*, size_t, size_t, void*);
+    using ErrorMsgBuf = std::array<char, CURL_ERROR_SIZE>;
```
Comment (kirkrodrigues) [inline components/core/src/clp/CurlDownloadHandler.hpp:34]: Nit: Can we make this the first type?

File: components/core/src/clp/CurlDownloadHandler.hpp [hunk 10]
```diff
@@ -37,6 +41,8 @@ class CurlDownloadHandler {
 
     // Constructor
     /**
+     * @param error_msg_buf The buffer to store the CURL error message if it is not `nullptr`.
```
Comment (kirkrodrigues) [inline components/core/src/clp/CurlDownloadHandler.hpp:44]:
```suggestion
     * @param error_msg_buf The buffer to store the CURL error message or `nullptr` if it shouldn't
     * be stored.
```

File: components/core/src/clp/CurlDownloadHandler.cpp [hunk 11]
```diff
@@ -17,7 +20,17 @@ CurlDownloadHandler::CurlDownloadHandler(
...
         std::chrono::seconds overall_timeout
-) {
+)
+        : m_error_msg_buf{std::move(error_msg_buf)} {
+    if (nullptr != m_error_msg_buf) {
+        // Set up error message buffer
+        // According to the doc: https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html
+        // A successful call of setting `CURLOPT_ERRORBUFFER` will initialize the buffer to an empty
+        // string since 7.60.0. The minimum version we require is 7.68.0. Therefore, we don't need
+        // to manually clean up the passed-in buffer.
```
Comment (kirkrodrigues) [inline components/core/src/clp/CurlDownloadHandler.cpp:30]:
```suggestion
        // According to the docs (https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html), since 7.60.0,
        // a successful call to set `CURLOPT_ERRORBUFFER` will initialize the buffer to an empty
        // string 7.60.0. Since we require at least 7.68.0, we don't need to clear the provided
        // buffer before it's used.
```

File: components/core/src/clp/CurlDownloadHandler.cpp [hunk 12]
```diff
@@ -46,5 +59,8 @@ CurlDownloadHandler::CurlDownloadHandler(
     if (false == m_http_headers.is_empty()) {
         m_easy_handle.set_option(CURLOPT_HTTPHEADER, m_http_headers.get_raw_list());
     }
+
+    // Set up failure on error
```
Comment (kirkrodrigues) [inline components/core/src/clp/CurlDownloadHandler.cpp:63]:
```suggestion
    // Set up failure on HTTP error reponse
```

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

**Review by kirkrodrigues — APPROVED** [review]
For the PR title, how about:

core: Add support for retrieving CURL error messages, handle unexpected CURL return code on macOS, and log such codes in tests (fixes #519).

**Comment by kirkrodrigues** [comment]
Can you:
* Update the PR description
* Comment on the workflow failures once they finish

**Comment by LinZhihao-723** [comment]
centOS build failed due to issue #521 which is not related to this PR.
