### PR TITLE
fix(core): Use a more reliable HTTP-header echo-server in unit tests (fixes #853).

### LINKED ISSUE #853: Unit tests that rely on httpbin.org fail intermittently.
### Bug

The NetworkReader unit tests that use https://httpbin.org ([1](https://github.com/y-scope/clp/blob/1b419f51b983b8ac4199a41f505ebe680a68112a/components/core/tests/test-NetworkReader.cpp#L195), [2](https://github.com/y-scope/clp/blob/1b419f51b983b8ac4199a41f505ebe680a68112a/components/core/tests/test-NetworkReader.cpp#L235)) have been failing frequently ([example](https://github.com/y-scope/clp/actions/runs/14668146350/job/41168029430)), albeit intermittently due to httpbin.org being a bit unreliable. 

<details>
<summary>Unit test failure logs</summary>

```text
-------------------------------------------------------------------------------
network_reader_with_valid_http_header_kv_pairs
-------------------------------------------------------------------------------
/mnt/repo/components/core/tests/test-NetworkReader.cpp:195
...............................................................................

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:100: warning:
  Unexpected CURL error code: 22; expected: 0
  Error message:
  The requested URL returned error: 503

/mnt/repo/components/core/tests/test-NetworkReader.cpp:227: FAILED:
  REQUIRE( optional_content.has_value() )
with expansion:
  false
```
</details>

### CLP version

1b419f51b983b8ac4199a41f505ebe680a68112a

### Environment

Any GitHub runner.

### Reproduction steps

Run either of the [clp-core-build](https://github.com/y-scope/clp/blob/1b419f51b983b8ac4199a41f505ebe680a68112a/.github/workflows/clp-core-build.yaml) or [clp-core-build-macos](https://github.com/y-scope/clp/blob/1b419f51b983b8ac4199a41f505ebe680a68112a/.github/workflows/clp-core-build-macos.yaml) workflows.

### PR DESCRIPTION
**Pull request by kirkrodrigues**
# Description

Switches the HTTP-header echo-server we use in unit tests from httpbin.org to mockhttp.org since the latter seems much more reliable.

Although we can't guarantee that mockhttp.org is more reliable than httpbin.org, the former at least seems to be [maintained](https://github.com/jaredwray/mockhttp) compared to httpbin.org whose source hasn't been updated in years.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

GH workflows succeeded.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

- **Tests**
  - Updated tests to use a new HTTP header echo server URL.
  - Enhanced header comparison logic to handle lowercase header names returned by the new server.
  - Added clarifying comments about header case handling in tests.

### CODE REVIEW

File: components/core/tests/test-NetworkReader.cpp [hunk 1]
```diff
@@ -22,9 +22,11 @@
 #include "../src/clp/NetworkReader.hpp"
 #include "../src/clp/Platform.hpp"
 #include "../src/clp/ReaderInterface.hpp"
+#include "../src/clp/string_utils/string_utils.hpp"
 
 namespace {
 constexpr size_t cDefaultReaderBufferSize{1024};
+constexpr std::string_view cHttpHeadersEchoServerUrl{"https://mockhttp.org/headers"};
```
Comment (anlowee) [inline components/core/tests/test-NetworkReader.cpp:29]: curious how do we know this is more reliable than current one

Comment (kirkrodrigues) [reply components/core/tests/test-NetworkReader.cpp:29]: We don't know for sure, but it seems to be better maintained and in my testing, it didn't fail once.

**Review by anlowee — APPROVED** [review]
