### PR TITLE
core: Add support for building on Centos Stream 9 and drop support for building on Centos 7.4 (fixes #521).

### LINKED ISSUE #521: cent OS image fails to build
### Bug

In current workflow, the centos image build fails on an error
`curl#6 - "Could not resolve host: mirrorlist.centos.org; Name or service not known"`

This seems to be due to cent OS EOL in 2024 June, which caused the mirrorlist.centos.org to be removed.

A possible solution is to [update all .repo files](https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve), which will result in a quite messy DockerFile.

Based an offline conversation with Kirk, cent OS is used by a very specific group of users. Perhaps we should first understand why they rely on cent OS 7 and decide whether to fix this bug or deprecate cent OS 7.4

### CLP version

e1f3f2abe3473324b19d66e22c182ec3ac0d408f

### Environment

the local env doesn't matter

### Reproduction steps

commit any change that would trigger workflow rerun and push it to your own repo.

For example, a simple change would be adding/deleting a comment in the cent OS's dockerfile.

### PR DESCRIPTION
**Pull request by kirkrodrigues**
# Description

As #521 mentions, CentOS [reached EoL](https://www.redhat.com/en/topics/linux/centos-linux-eol) on 2024-Jun-30, so its default mirror list no longer exists. It seems like [some folks](https://github.com/facebookincubator/velox?tab=readme-ov-file#setting-up-on-centos-9-stream-with-adapters) have moved to CentOS Stream 9.

This PR adds support for building on CentOS Stream 9 and drops support for building on CentOS 7.4. We can't say for sure if this will affect existing users, but hopefully they will file an issue if it does.

Note that:

* We don't support static linking on CentOS Stream 9 since it doesn't seem to have static library packages like CentOS 7.4 did.
  * To support static library building, we would need to write build scripts for several packages, so for now, we'll defer that work until a user asks.
* The MariaDB C Connector package on CentOS Stream 9 requires that we include `mysql.h` directly rather than as a file within `mariadb`, so this PR updates all references to do the same.
  * The way we were including `mysql.h` before was essentially using the include from the system-include directory, bypassing the CMake config script (which sets the include dir to `<system-include-dir>/mariadb` already), so this is more correct.

# Validation performed

* Validated [clp-core-build](https://github.com/y-scope/clp/blob/main/.github/workflows/clp-core-build.yaml) passed.
* Validated compression, decompression, and search with the clp-package (to exercise the MariaDB/MySQL code paths in core).

### CODE REVIEW

File: components/core/tools/scripts/lib_install/centos-stream-9/install-packages-from-source.sh [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+# Exit on any error
+set -e
+
+# Error on undefined variable
+set -u
+
+script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+lib_install_scripts_dir="${script_dir}/.."
+
+# NOTE: The remaining installation scripts depend on and boost, so we install it beforehand.
```
Comment (LinZhihao-723) [inline components/core/tools/scripts/lib_install/centos-stream-9/install-packages-from-source.sh:12]:
```suggestion
# NOTE: The remaining installation scripts depend on boost, so we install it beforehand.
```

**Review by LinZhihao-723 — CHANGES_REQUESTED** [review]

File: components/core/CMakeLists.txt [hunk 2]
```diff
@@ -51,10 +51,20 @@ endif()
...
+        set(CLP_STATIC_LIBS_UNSUPPORTED_PLATFORM "macOS")
+    elseif (EXISTS "/etc/centos-release")
+        set(CLP_STATIC_LIBS_UNSUPPORTED_PLATFORM "CentOS")
+    endif()
+
+    if (DEFINED CLP_STATIC_LIBS_UNSUPPORTED_PLATFORM)
+        message(
+            AUTHOR_WARNING
+            "Building with static libraries is unsupported on \
+${CLP_STATIC_LIBS_UNSUPPORTED_PLATFORM}. Switching to shared libraries.")
```
[the remark this answers is not in the document]
Comment (kirkrodrigues) [reply components/core/CMakeLists.txt]: Sorry, my mistake.

File: components/core/CMakeLists.txt [hunk 3]
```diff
@@ -51,10 +51,20 @@ endif()
...
+        set(CLP_STATIC_LIBS_UNSUPPORTED_PLATFORM "macOS")
+    elseif (EXISTS "/etc/centos-release")
+        set(CLP_STATIC_LIBS_UNSUPPORTED_PLATFORM "CentOS")
+    endif()
+
+    if (DEFINED CLP_STATIC_LIBS_UNSUPPORTED_PLATFORM)
+        message(
+            AUTHOR_WARNING
+            "Building with static libraries is unsupported on"
+            " ${CLP_STATIC_LIBS_UNSUPPORTED_PLATFORM}. Switching to shared libraries.")
```
Comment (kirkrodrigues) [inline components/core/CMakeLists.txt:65]: I put the space on this line to follow our code style of putting operators, etc. at the beginning of a broken line.

**Review by LinZhihao-723 — APPROVED** [review]
