### PR TITLE
clo: Fix a bug causing pure wildcard queries to return no results (fixes #342)

### LINKED ISSUE #342: clp: Queries for `*` from the package/webui don't return any results.
### Bug

When using `clp` as the storage engine, queries for `*` from either `sbin/search.sh` in the package or the webui both don't return any results even when there's compressed data.

### CLP version

6946f02

### Environment

Ubuntu 20.04

### Reproduction steps

* Build a package

  ```shell
  task package
  ```

* Start the package

  ```shell
  cd build/clp-package
  sbin/start-clp.sh
  ```

* Compress some data

  ```shell
  sbin/compress.sh <dataset>
  ```

* Search for some data

  ```shell
  sbin/search.sh '*'
  ```

No results will be returned.

### PR DESCRIPTION
**Pull request by wraymo**
# References

#342 

# Description

Previously clo didn't return any results for pure wildcard queries `*` because it skips searching each file. This PR resolves this issue.

# Validation performed

+ Built clo and compressed [hive-24hrs](https://zenodo.org/records/7094921#.Y5JbH33MKHs) logs using clp.
+ Executed query `*` on one of the archives using clo and output results to MongoDB.
+ Checked the corresponding collection in MongoDB.

### CODE REVIEW

File: components/core/src/clp/clo/clo.cpp [hunk 1]
```diff
@@ -93,7 +93,9 @@ static SearchFilesResult search_files(
 
     // Run query on each file
     for (; file_metadata_ix.has_next(); file_metadata_ix.next()) {
-        if (segments_to_search.count(file_metadata_ix.get_segment_id()) == 0) {
+        if (query.contains_sub_queries()
```
Comment (kirkrodrigues) [inline components/core/src/clp/clo/clo.cpp:96]: Do you not want to use clg's logic instead? Namely:

* if there are no subqueries:
  * search all files
* else if there are subqueries:
  * for each segment matching a subquery:
    * search each file within the segment
    
I think the logic above should be more efficient by avoiding some branches.

Comment (wraymo) [reply components/core/src/clp/clo/clo.cpp:96]: Because we want to order files by timestamps, if we follow clg's logic to search each file within a segment, we cannot guarantee this order.

Comment (wraymo) [reply components/core/src/clp/clo/clo.cpp:96]: Which branches do you think we can avoid?

Comment (kirkrodrigues) [reply components/core/src/clp/clo/clo.cpp:96]: Ah, right, forgot about the timestamp sorting. We can still have separate cases for no-subqueries vs subqueries, right? That way we don't repeat the no-subqueries check for every file that we search.

**Comment by wraymo** [comment]
updated it. still some duplicate code

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

File: components/core/src/clp/clo/clo.cpp [hunk 2]
```diff
@@ -78,71 +91,94 @@ static bool search_archive(
...
+void search_files(
+        Query& query,
+        Archive& archive,
+        MetadataDB::FileIterator& file_metadata_ix,
+        std::unique_ptr<OutputHandler>& output_handler,
+        std::set<clp::segment_id_t> const& segments_to_search
+) {
+    if (query.contains_sub_queries()) {
+        for (; file_metadata_ix.has_next(); file_metadata_ix.next()) {
+            if (segments_to_search.count(file_metadata_ix.get_segment_id()) > 0) {
```
[the remark this answers is not in the document]
Comment (wraymo) [reply components/core/src/clp/clo/clo.cpp]: Right

**Review by kirkrodrigues — APPROVED** [review]
How about:

clo: Handle case where non-null query doesn't generate subqueries (fixes #342). (#345)

**Comment by wraymo** [comment]
> How about:
> 
> clo: Handle case where non-null query doesn't generate subqueries (fixes #342). (#345)

It might be a little bit unclear what we are doing in this PR? It seems that we're trying to generate subqueries for non-null queries that currently do not generate them.

**Comment by kirkrodrigues** [comment]
> It might be a little bit unclear what we are doing in this PR? It seems that we're trying to generate subqueries for non-null queries that currently do not generate them.

Fair. How about:

clo: Handle pure-wildcard query (fixes #342). (#345)
