### PR TITLE
fix(webui): Proxy socket.io requests when localhost resolves to multiple addresses (fixes #1062).

### LINKED ISSUE #1062: WebUI search returns no results when localhost resolves to IPv6
(issue originally reported by @haiqi96 ; @davemarco helped investigated)
### Bug

Search queries through the WebUI consistently return no results. When investigating the network traffic, the search endpoint returns the React app's index.html content instead of the expected socket.io responses. This issue appears to be related to localhost resolving to IPv6 addresses on affected systems.

### CLP version

35208950df5acf38ff8f0c560abee65a61b28703

### Environment

Windows 11 + Windows Docker Engine
The package was running in WSL Ubuntu Jammy

### Reproduction steps

1. Start the package with default settings and compress sample logs.
2. Navigate to http://localhost:4000/search in a web browser
3. Perform a search using any query string (e.g., "*")
4. Observe that no search results are returned
5. Open browser developer tools and check the Network tab
6. Notice that the search request returns index.html content instead of socket.io responses
7. Verify that this occurs on systems where localhost resolves to IPv6 addresses

### PR DESCRIPTION
**Pull request by junhaoliao**
# Description

See the analysis at #1062 . This PR implements "Approach 5" which is the final recommendation.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

On Windows:
1. Installed Docker Desktop for Windows. "Enable host networking" in the Settings -> Resources -> Network.
2. Within a WSL 2 VM (Ubuntu Jammy), added the default user to the `docker` group: `sudo usermod -aG docker "$USER"`.

Within the WSL VM:
1. Built the package: `task`
2. Started the package: `cd build/clp-package/sbin; ./start-clp.sh`
3. Compressed sample logs: `./compress.sh ~/sample/hive-24hr/i-00c90a0f/`
4. Launched the WebUI in a browser: http://localhost:4000/search . Performed a search with query string being "1" and observed "found 29099 results" in the UI within a second of query submission.
5. Repeated Step 4 with http://127.0.0.1:4000/search and observed the same results.
6. Repeated Step 4 with http://[::1]:4000/search and observed the same results.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

* **New Features**
  * Enhanced server to proxy socket.io requests across multiple IP addresses, including IPv4 and IPv6, ensuring seamless connectivity.  
* **Chores**
  * Added a dependency to support HTTP proxy functionality.

### CODE REVIEW

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts [hunk 1]
```diff
@@ -77,6 +81,35 @@ class MongoSocketIoServer {
...
+        // Fastify listens on all resolved addresses for localhost (e.g. `127.0.0.1`, `::1`), but
+        // socket.io only uses the main one. When multiple addresses are resolved, we proxy
+        // socket.io requests from secondary addresses to the main server.
+        dnsLookup(fastify.config.HOST, {all: true}, (err, addresses) => {
+            if (null !== err) {
+                fastify.log.error(`DNS lookup failed: ${err.message}`);
+
+                return;
+            }
+            const [firstAddress] = addresses;
```
Comment (junhaoliao) [inline components/webui/server/src/plugins/MongoSocketIoServer/index.ts]:
```suggestion

            const [firstAddress] = addresses;
```

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts [hunk 2]
```diff
@@ -77,6 +81,35 @@ class MongoSocketIoServer {
...
+            if ("undefined" === typeof firstAddress) {
+                fastify.log.error("No addresses found for the provided host.");
+
+                return;
+            }
+            if (1 < addresses.length) {
```
Comment (junhaoliao) [inline components/webui/server/src/plugins/MongoSocketIoServer/index.ts]:
```suggestion

            if (1 < addresses.length) {
```

**Comment by davemarco** [comment]
I can't test this since mac (maybe @haiqi96), but from what you described the approach makes sense. Do we need this fix for the release?

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts [hunk 3]
```diff
@@ -77,6 +81,30 @@ class MongoSocketIoServer {
...
+                return;
+            }
+
+            if (1 < addresses.length) {
+                fastify.log.warn(
+                    `Multiple addresses found for ${fastify.config.HOST}: ${
+                        JSON.stringify(addresses)}. ` +
+                    "Proxying all socket.io requests to the main server."
+                );
+                fastify.register(fastifyHttpProxy, {
```
Comment (davemarco) [inline components/webui/server/src/plugins/MongoSocketIoServer/index.ts]: you may beable to get https/http from fastify.initialConfig.https, so not hardcoded at http

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts [hunk 4]
```diff
@@ -77,6 +81,30 @@ class MongoSocketIoServer {
             InterServerEvents,
             SocketData
         >(fastify.server);
+
+        // Fastify listens on all resolved addresses for localhost (e.g. `127.0.0.1`, `::1`), but
+        // socket.io only uses the main one. When multiple addresses are resolved, we proxy
+        // socket.io requests from secondary addresses to the main server.
+        dnsLookup(fastify.config.HOST, {all: true}, (err, addresses) => {
```
Comment (davemarco) [inline components/webui/server/src/plugins/MongoSocketIoServer/index.ts]: you could potentially do this with fastify.addresses property instead, but you would need to call in the main.ts file and after fastify.listen(after plugin registration). Overall I think the approach you took where it is done in the this plugin is better.

Comment (junhaoliao) [reply components/webui/server/src/plugins/MongoSocketIoServer/index.ts]: right, i believe the Fastify addresses info isn't available until `fastify.listen()` is called. also as you mentioned the proxy registration within this Mongo plugin was intentional.

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts (hunk 3 above)
Comment (junhaoliao) [reply components/webui/server/src/plugins/MongoSocketIoServer/index.ts]: we don't support HTTPS cert configuration in the Fastify server yet so this may not matter. still, i made the change to show the consideration.

until we add HTTPS support in the fastify server and disable HTTP when deployment maintainers configure so, it's recommended to protect the HTTP server with an HTTPS-enabled Nginx reverse proxy

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts [hunk 5]
```diff
@@ -92,6 +95,34 @@ class MongoSocketIoServer {
...
+        // Fastify listens on all resolved addresses for localhost (e.g. `127.0.0.1`, `::1`), but
+        // socket.io only uses the main one. When multiple addresses are resolved, we proxy
+        // socket.io requests from secondary addresses to the main server.
+        try {
+            const addresses = await dnsLookup(fastify.config.HOST, {all: true});
+            if (1 < addresses.length) {
+                fastify.log.warn(
+                    `Multiple addresses found for ${fastify.config.HOST}: ${
+                        JSON.stringify(addresses)}. ` +
+                    "Proxying all socket.io requests to the main server."
```
[the remark this answers is not in the document]
Comment (junhaoliao) [reply components/webui/server/src/plugins/MongoSocketIoServer/index.ts:109]: it was broken down to avoid line length violation of max 100 characters

**Comment by junhaoliao** [comment]
> I can't test this since mac (maybe @haiqi96), but from what you described the approach makes sense. Do we need this fix for the release?

Hey @haiqi96 , could you confirm this is tested on your WSL + Docker Desktop setup?

---

Due to the nature of the issue (i.e., Fastify listens on all addresses when `localhost` can be resolved into multiple ones), I believe it's also possible to test on Mac / Linux by:
1. Edit `/etc/hosts` to allow `localhost` to resolve to both `127.0.0.1` and `::1`. e.g.,
    ```
    127.0.0.1 localhost
    ::1 localhost
    ```
2. Start the fastify server
3. Access http://127.0.0.1/search and perform a search; observe the search does not hang.
4. Access http://[::1]/search and perform a search; observe the search does not hang.

**Comment by haiqi96** [comment]
> > I can't test this since mac (maybe @haiqi96), but from what you described the approach makes sense. Do we need this fix for the release?
> 
> Hey @haiqi96 , could you confirm this is tested on your WSL + Docker Desktop setup?
> 
> Due to the nature of the issue (i.e., Fastify listens on all addresses when `localhost` can be resolved into multiple ones), I believe it's also possible to test on Mac / Linux by:
> 
> 1. Edit `/etc/hosts` to allow `localhost` to resolve to both `127.0.0.1` and `::1`. e.g.,
>    ```
>    127.0.0.1 localhost
>    ::1 localhost
>    ```
> 2. Start the fastify server
> 3. Access http://127.0.0.1/search and perform a search; observe the search does not hang.
> 4. Access http://[::1]/search and perform a search; observe the search does not hang.

Yes I have tested it in the morning.

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts [hunk 6]
```diff
@@ -92,6 +95,34 @@ class MongoSocketIoServer {
         options: DbOptions
     ): Promise<MongoSocketIoServer> {
         const mongoDb = await initializeMongoClient(options);
+
+        // Fastify listens on all resolved addresses for localhost (e.g. `127.0.0.1`, `::1`), but
+        // socket.io only uses the main one. When multiple addresses are resolved, we proxy
```
Comment (davemarco) [inline components/webui/server/src/plugins/MongoSocketIoServer/index.ts]:
```suggestion
        // socket.io can only receive the primary address from Fastify. When multiple addresses are resolved, we proxy
```

**Comment by davemarco** [comment]
I tested this on linux, and confirmed does not break anything. If required, this can be merged. I am discussing an alternate approach with junhao. The alternate approach is slightly worse but does not require a new dependency or unelegant code (style is good, but it inevitably it would look strange to a new dev on project) . currently weighing options, but this can be merged and we can decide later as well.

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts (hunk 6 above)
Comment (junhaoliao) [reply components/webui/server/src/plugins/MongoSocketIoServer/index.ts]: how about
```suggestion
        // socket.io can only intercept requests on the main server which listens only on the primary address. When multiple addresses are resolved, we proxy
```

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts [hunk 7]
```diff
@@ -92,6 +95,34 @@ class MongoSocketIoServer {
         options: DbOptions
     ): Promise<MongoSocketIoServer> {
         const mongoDb = await initializeMongoClient(options);
+
+        // Fastify listens on all resolved addresses for localhost (e.g. `127.0.0.1`, `::1`), but
```
Comment (junhaoliao) [inline components/webui/server/src/plugins/MongoSocketIoServer/index.ts]:
```suggestion
        // Fastify listens on all resolved addresses for localhost (e.g. `::1` and `127.0.0.1`), but
```

Comment (davemarco) [reply components/webui/server/src/plugins/MongoSocketIoServer/index.ts]: happy for u to commit this. If i commit i cant approve

File: components/webui/server/src/plugins/MongoSocketIoServer/index.ts (hunk 6 above)
Comment (davemarco) [reply components/webui/server/src/plugins/MongoSocketIoServer/index.ts]: happy for u to commit this. If i commit i cant approve

**Comment by junhaoliao** [comment]
@coderabbitai open an issue about making the socket.io transport (e.g., ws only, polling only, or both) configurable in `clp-config.yml`

**Comment by junhaoliao** [comment]
> I tested this on linux, and confirmed does not break anything. If required, this can be merged. I am discussing an alternate approach with junhao. The alternate approach is slightly worse but does not require a new dependency or unelegant code (style is good, but it inevitably it would look strange to a new dev on project) . currently weighing options, but this can be merged and we can decide later as well.

@davemarco the rabbit has helped to create an issue at #1092 about the transport config option we discussed offline. I believe it will be a good opportunity to revisit the changes in the current PR when we implement #1092 .
