### PR TITLE
fix(clp-rust-utils): Configure AWS region and credentials in base config to avoid default provider resolution (fixes #1915).

### LINKED ISSUE #1915: AWS SDK IMDS lookups cause 3-second delay in log-ingestor job creation
### Bug

When creating an S3 scanner ingestion job via the log-ingestor API, the AWS SDK attempts to load region information from EC2 Instance Metadata Service (IMDS), even though the region is explicitly provided in the request. This causes:

1. **3-second delay** during job creation (3 x 1-second IMDS timeout retries)
2. **Spurious warning logs** that may confuse operators:
   ```
   {"level":"WARN","message":"failed to load region from IMDS","err":"failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out"}
   ```

**Expected behavior:** When region and credentials are explicitly provided, the AWS SDK should not attempt to load configuration from IMDS or other environment sources.

## Root Cause

https://github.com/y-scope/clp/blob/01d35a672c2f6fb892912121800b7a85f7448b23/components/clp-rust-utils/src/s3/client.rs#L32

The `load().await` call triggers the AWS SDK's default credential/region provider chain, which includes IMDS as a fallback. In non-EC2 environments, IMDS is unreachable, causing timeout retries.

## Potential fix

Build the S3/SQS client configuration directly without using the default environment provider chain, since credentials and region are already explicitly provided by the caller.

See: https://docs.rs/aws-config/latest/aws_config/struct.ConfigLoader.html
> Overriding a component will skip the standard resolution chain from for that component.

Then, in theory, this should get rid of the environment variable provider chain:
```rust
    let config = aws_config::defaults(BehaviorVersion::latest())
        .credentials_provider(credentials)
        .region(Region::new(region_id.to_string()))
        .load()
        .await;

    let mut s3_config_builder = Builder::from(&config).force_path_style(true);
    s3_config_builder.set_endpoint_url(endpoint.map(std::string::ToString::to_string));
    Client::from_conf(s3_config_builder.build())
```

### CLP version

01d35a672c2f6fb892912121800b7a85f7448b23

### Environment

- Kubernetes cluster (local, non-EC2 environment)
- Helm chart deployment with `logs_input.type: "s3"`
- log-ingestor pod running

### Reproduction steps

1. Deploy CLP using the Helm chart with S3 logs input:
   ```yaml
   clpConfig:
     logs_input:
       type: "s3"
       aws_authentication:
         type: "credentials"
         credentials:
           access_key_id: "<your-access-key>"
           secret_access_key: "<your-secret-key>"
   ```

2. Create an S3 scanner ingestion job:
   ```bash
   curl --location 'localhost:30302/s3_scanner' \
     --header 'Content-Type: application/json' \
     --data '{
       "bucket_name": "your-bucket",
       "key_prefix": "/",
       "region": "us-east-2"
     }'
   ```

3. Observe the log-ingestor logs:
   ```bash
   kubectl logs -f <log-ingestor-pod>
   ```

4. Notice the IMDS timeout warnings and the ~3-second delay before the job is created.

### PR DESCRIPTION
**Pull request by LinZhihao-723**
# Description

As the title suggests, this PR implements the suggested fix in #1915 to avoid unnecessary IMDS lookups.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

* [x] Ensure all workflows pass.
* [x] Created both S3 scanning and SQS listening jobs. Ensure that with the fix applied, there is no IMDS lookup overhead. log-ingestor log:
  ```
  {"timestamp":"2026-01-28T20:34:02.705660Z","level":"INFO","fields":{"message":"Server started at 0.0.0.0:3002"},"filename":"components/log-ingestor/src/bin/log_ingestor.rs","line_number":103}
  {"timestamp":"2026-01-28T20:34:16.492677Z","level":"INFO","fields":{"message":"Create SQS listener ingestion job.","config":"SqsListenerConfig { base: BaseConfig { bucket_name: NonEmptyString(\"lzh-test\"), key_prefix: NonEmptyString(\"test-1769632456\"), region: Some(NonEmptyString(\"us-east-2\")), endpoint_url: None, dataset: None, timestamp_key: None, unstructured: false }, queue_url: NonEmptyString(\"https://sqs.us-east-2.amazonaws.com/568954113123/log-ingestor-sqs-test\") }"},"filename":"components/log-ingestor/src/routes.rs","line_number":218}
  {"timestamp":"2026-01-28T20:34:16.520597Z","level":"INFO","fields":{"message":"Created SQS listener ingestion job.","job_id":"5dd9d9a2-5f4d-471b-9b9f-d0a40051d08d"},"filename":"components/log-ingestor/src/routes.rs","line_number":226}
  {"timestamp":"2026-01-28T20:34:23.139606Z","level":"INFO","fields":{"message":"Received new object metadata from SQS.","object":"ObjectMetadata { bucket: NonEmptyString(\"lzh-test\"), key: NonEmptyString(\"test-1769632456/log_1769632457.clp.zstd\"), size: 6748 }"},"filename":"components/log-ingestor/src/ingestion_job/sqs_listener.rs","line_number":103}
  {"timestamp":"2026-01-28T20:34:27.732227Z","level":"INFO","fields":{"message":"Received new object metadata from SQS.","object":"ObjectMetadata { bucket: NonEmptyString(\"lzh-test\"), key: NonEmptyString(\"test-1769632456/log_1769632462.clp.zstd\"), size: 6731 }"},"filename":"components/log-ingestor/src/ingestion_job/sqs_listener.rs","line_number":103}
  {"timestamp":"2026-01-28T20:34:36.143491Z","level":"INFO","fields":{"message":"Received new object metadata from SQS.","object":"ObjectMetadata { bucket: NonEmptyString(\"lzh-test\"), key: NonEmptyString(\"test-1769632456/log_1769632467.clp.zstd\"), size: 6776 }"},"filename":"components/log-ingestor/src/ingestion_job/sqs_listener.rs","line_number":103}
  {"timestamp":"2026-01-28T20:34:41.682829Z","level":"INFO","fields":{"message":"Received new object metadata from SQS.","object":"ObjectMetadata { bucket: NonEmptyString(\"lzh-test\"), key: NonEmptyString(\"test-1769632456/log_1769632475.clp.zstd\"), size: 6754 }"},"filename":"components/log-ingestor/src/ingestion_job/sqs_listener.rs","line_number":103}
  {"timestamp":"2026-01-28T20:34:46.256316Z","level":"INFO","fields":{"message":"Received new object metadata from SQS.","object":"ObjectMetadata { bucket: NonEmptyString(\"lzh-test\"), key: NonEmptyString(\"test-1769632456/log_1769632481.clp.zstd\"), size: 6721 }"},"filename":"components/log-ingestor/src/ingestion_job/sqs_listener.rs","line_number":103}
  {"timestamp":"2026-01-28T20:35:10.734166Z","level":"INFO","fields":{"message":"Create S3 scanner ingestion job.","config":"S3ScannerConfig { base: BaseConfig { bucket_name: NonEmptyString(\"lzh-test\"), key_prefix: NonEmptyString(\"test-1769632511\"), region: Some(NonEmptyString(\"us-east-2\")), endpoint_url: None, dataset: None, timestamp_key: None, unstructured: false }, scanning_interval_sec: 30, start_after: None }"},"filename":"components/log-ingestor/src/routes.rs","line_number":167}
  {"timestamp":"2026-01-28T20:35:10.734596Z","level":"INFO","fields":{"message":"Created S3 scanner ingestion job.","job_id":"5b7dac86-74ec-4a9b-88b8-dc111be87654"},"filename":"components/log-ingestor/src/routes.rs","line_number":175}
  {"timestamp":"2026-01-28T20:40:16.514338Z","level":"INFO","fields":{"message":"Submitting CLP compression job..."},"filename":"components/log-ingestor/src/compression/compression_job_submitter.rs","line_number":132}
  {"timestamp":"2026-01-28T20:40:16.516975Z","level":"INFO","fields":{"message":"Compression job submitted with ID: 1"},"filename":"components/log-ingestor/src/compression/compression_job_submitter.rs","line_number":144}
  {"timestamp":"2026-01-28T20:40:19.520901Z","level":"INFO","fields":{"message":"Compression job 1 completed successfully."},"filename":"components/log-ingestor/src/compression/compression_job_submitter.rs","line_number":187}
  ```

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

* **Chores**
  * Streamlined internal AWS client configuration for S3 and SQS to simplify initialization and ownership.
  * Adjusted internal handling of region and endpoint setup and corrected an internal credential provider identifier.
  * No changes to functionality, public interfaces, or exported declarations.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: components/clp-rust-utils/src/s3/client.rs [hunk 1]
```diff
@@ -29,11 +29,12 @@ pub async fn create_new_client(
         None,
         "clp-credential-provider",
     );
```
Comment (junhaoliao) [inline components/clp-rust-utils/src/s3/client.rs:31]: (though unrelated to the PR)

Can we rename `credential` -> `credentials` since the struct is named `Credentials`?

File: components/clp-rust-utils/src/s3/client.rs [hunk 2]
```diff
@@ -29,11 +29,12 @@ pub async fn create_new_client(
...
-    let base_config = aws_config::defaults(BehaviorVersion::latest()).load().await;
-    let mut config_builder = Builder::from(&base_config)
-        .credentials_provider(credential)
-        .region(Some(Region::new(region_id.to_string())))
-        .force_path_style(true);
+    let base_config = aws_config::defaults(BehaviorVersion::latest())
+        .credentials_provider(credential.clone())
```
Comment (junhaoliao) [inline components/clp-rust-utils/src/s3/client.rs]: The `credential` variable does not seemed used after this call so no need to `clone()`? also it's not consistent with the sqs client

```suggestion
        .credentials_provider(credential)
```

File: components/clp-rust-utils/src/sqs/client.rs [hunk 3]
```diff
@@ -25,10 +25,12 @@ pub async fn create_new_client(
         None,
         "clp-credential-provider",
     );
-    let base_config = aws_config::defaults(BehaviorVersion::latest()).load().await;
-    let mut config_builder = Builder::from(&base_config)
+    let base_config = aws_config::defaults(BehaviorVersion::latest())
         .credentials_provider(credential)
-        .region(Some(Region::new(region_id.to_string())));
+        .region(Some(Region::new(region_id.to_string())))
```
Comment (junhaoliao) [inline components/clp-rust-utils/src/sqs/client.rs]: seems like both `Region` and `Option<Region>` work

for consistency with the s3 client, shall we?
```suggestion
        .region(Region::new(region_id.to_string()))
```

**Review by junhaoliao — CHANGES_REQUESTED** [review]
validated the fix worked correctly:
* No IMDS delays: Job creation + S3 client initialization completed in ~230-307ms (vs. 3+ seconds before the fix)
* No spurious WARN logs: Zero "failed to load region from IMDS" messages

```bash
task docker-images:package
```

then modify `tools/deployment/package-helm/set-up-test.sh`
```bash
# Load the locally-built clp-package image into kind
repo_root="${script_dir}/../../../"
iid_file="${repo_root}/build/clp-package-image.id"
if [[ -f "$iid_file" ]]; then
    image_id=$(<"$iid_file")
    user="${USER:-$(id -un 2>/dev/null || whoami 2>/dev/null || echo unknown)}"
    short_id="${image_id#sha256:}"
    short_id="${short_id:0:4}"
    image_tag="dev-${user}-${short_id}"
    echo "Loading clp-package:${image_tag} into kind cluster..."
    kind load docker-image "clp-package:${image_tag}" --name "${CLUSTER_NAME}"
else
    echo "ERROR: No locally-built image found at ${iid_file}. Run 'task docker-images:package' first."
    exit 1
fi
```

Then Helm install with overrides to use the local image:

```bash
helm install test "${script_dir}" \
    --set "image.clpPackage.repository=clp-package" \
    --set "image.clpPackage.tag=${image_tag}" \
    --set "image.clpPackage.pullPolicy=Never"
```

then tested with the instructions at #1913

**Review by junhaoliao — APPROVED** [review]

**Review by junhaoliao — APPROVED** [review]
for the title, how about:
```
fix(clp-rust-utils): Configure AWS region and credentials in base config to avoid default provider resolution (fixes #1915).
```
