### PR TITLE
fix(docker): Remove `update-ca-trust`/`update-ca-certificates` dependency in corporate proxy CA setup (fixes #2116)

### LINKED ISSUE #2116: bug(docker): setup-corporate-proxy.sh fails on Ubuntu Jammy — update-ca-certificates not available before package installation
## Description

`components/core/tools/docker-images/clp-env-base-ubuntu-jammy/build.sh` fails when `setup-corporate-proxy.sh` is executed inside the container build, with the following error:

```
setup-corporate-proxy: installing corporate CA certificates...
setup-corporate-proxy: WARNING: no recognized CA trust update tool found.
ERROR: failed to build: failed to solve: process "/bin/sh -c ./tools/scripts/lib_install/setup-corporate-proxy.sh" did not complete successfully: exit code: 1
```

## Root Cause

`setup-corporate-proxy.sh` is executed early in the Dockerfile (step 5/8), **before** `install-all.sh` runs. The script requires either `update-ca-trust` (RHEL/CentOS) or `update-ca-certificates` (Debian/Ubuntu) to be present. On Ubuntu Jammy, `update-ca-certificates` is provided by the `ca-certificates` package, which is **not pre-installed** in the `ubuntu:jammy` base Docker image. As a result, neither tool is available at the time the script runs, causing it to exit with code 1.

## Steps to Reproduce

```bash
cd components/core/tools/docker-images/clp-env-base-ubuntu-jammy
./build.sh
```

## Expected Behaviour

`setup-corporate-proxy.sh` should either install `ca-certificates` first (or have it pre-installed) before attempting to update the trust store, or gracefully handle the case where `update-ca-certificates` is not yet available by installing the package inline.

## Suggested Fix

In the Ubuntu Jammy Dockerfile, add an `apt-get install -y --no-install-recommends ca-certificates` step (or include it in the same `RUN` layer) before invoking `setup-corporate-proxy.sh`. This ensures `update-ca-certificates` is available when the proxy setup script executes.

Note: The Alpine-based images (musllinux_1_2) may have a similar issue depending on whether `ca-certificates` is pre-installed in the Alpine base image.

## References

- PR: https://github.com/y-scope/clp/pull/1991
- Reported by: @junhaoliao

### PR DESCRIPTION
**Pull request by jackluo923**
# Description

`setup-corporate-proxy.sh` failed on `ubuntu:jammy` because neither `update-ca-trust` nor
`update-ca-certificates` is available in the base Docker image — the `ca-certificates` package
that provides these tools isn't installed until a later Dockerfile step.

Instead of adding a dependency on distro-specific trust update tools, this PR takes a simpler
approach: the host's CA bundle is already a combined trust store, so we copy it directly to
`/opt/corp-ca/ca-bundle.crt` inside the container. This path is outside the system package
manager's control, so it survives reinstalls of `ca-certificates` that regenerate the system
bundle. The Dockerfile `ENV` vars (`SSL_CERT_FILE`, `CURL_CA_BUNDLE`, etc.) point tools at
this path.

Additional changes in this PR:
- Rename `proxy-lib.sh` → `corporate-proxy-host.sh` and `setup-corporate-proxy.sh` →
  `corporate-proxy-container.sh` to clarify host vs container roles.
- Move both scripts to `components/core/tools/scripts/` alongside each other.
- Update ENV vars in **all** Dockerfiles (not just Ubuntu) to use `/opt/corp-ca/ca-bundle.crt`.
- Re-declare ENV vars after `FROM scratch` in CentOS and Ubuntu Dockerfiles (ENV doesn't
  carry across multi-stage `FROM` boundaries).
- Add CI workflow step to stage the runner's system CA bundle before `docker build`.
- Remove the committed empty `ca-certificates.crt` placeholder; the file is now always
  generated at build time and gitignored. Empty/missing files error instead of silently
  producing broken images.
- Fix macOS compatibility (bash 3.x lacks namerefs).
- Update `docs/src/dev-docs/tooling-containers.md` to reference the renamed script.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

- Built `clp-env-base-ubuntu-jammy` Docker image successfully (previously failed at step 5/8).
- Built `clp-env-base-manylinux_2_28`, `clp-env-base-musllinux_1_2`, and
  `clp-env-base-centos-stream-9` Docker images successfully on both x86_64 and aarch64.
- Verified the corporate proxy CA script correctly detects and copies the host CA bundle.
- Verified that an empty/missing `ca-certificates.crt` errors with a clear message.
- Tested within a corporate environment on macOS and Debian.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

### CODE REVIEW

File: components/core/tools/scripts/corporate-proxy-container.sh [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+
+if [[ ! -s "$ca_cert" ]]; then
+    # No corporate proxy — create the stable bundle from the system certs so
+    # that env vars (PIP_CERT, CURL_CA_BUNDLE, etc.) pointing to it are valid.
+    echo "corporate-proxy-container: no corporate CA bundle provided; using system certs."
+    mkdir -p /opt/corp-ca
+    cp /etc/ssl/certs/ca-certificates.crt /opt/corp-ca/ca-bundle.crt 2>/dev/null \
+        || cp /etc/pki/tls/certs/ca-bundle.crt /opt/corp-ca/ca-bundle.crt 2>/dev/null \
+        || touch /opt/corp-ca/ca-bundle.crt
+    exit 0
```
[the remark this answers is not in the document]
Comment (jackluo923) [reply components/core/tools/scripts/corporate-proxy-container.sh]: Addressed — the container script now errors on empty/missing ca-certificates.crt instead of creating an empty bundle. The host script and CI workflow always stage a valid CA bundle.

File: components/core/tools/scripts/corporate-proxy-host.sh [hunk 2]
```diff
@@ -45,7 +49,7 @@ detect_ca_bundle() {
 #   $1 - component_root (path to components/core/)
 prepare_ca_cert_for_build() {
     local component_root="$1"
-    local dest="${component_root}/tools/scripts/lib_install/ca-certificates.crt"
+    local dest="${component_root}/tools/scripts/ca-certificates.crt"
```
[the remark this answers is not in the document]
Comment (jackluo923) [reply components/core/tools/scripts/corporate-proxy-host.sh:54]: Addressed — removed the committed placeholder from the repo and added it to .gitignore. The file is now always generated at build time by the host script (local builds) or CI workflow step.

File: components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile [hunk 3]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
-    REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
-    PIP_CERT=/etc/ssl/certs/ca-certificates.crt
+# Point pip/pipx and curl at the corporate CA bundle path set by corporate-proxy-container.sh.
+# This path is outside the system package manager's control, so it survives reinstalls of
+# ca-certificates (which regenerates the system bundle). When no corporate proxy is in use,
+# this path won't exist; tools fall back to their built-in defaults which work fine without a proxy.
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
+    CURL_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
+    REQUESTS_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
+    PIP_CERT=/opt/corp-ca/ca-bundle.crt
```
[the remark this answers is not in the document]
Comment (jackluo923) [reply components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile]: Addressed — ca-certificates.crt is now always a valid CA bundle (either corporate certs or system certs). The container script errors if the file is empty/missing, and both the host script and CI workflow ensure a valid bundle is staged before docker build.

File: components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile [hunk 4]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
-    REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt \
-    PIP_CERT=/etc/pki/tls/certs/ca-bundle.crt
+# Point pip/pipx and curl at the corporate CA bundle path set by corporate-proxy-container.sh.
+# This path is outside the system package manager's control, so it survives reinstalls of
+# ca-certificates (which regenerates the system bundle). When no corporate proxy is in use,
+# this path won't exist; tools fall back to their built-in defaults which work fine without a proxy.
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
+    CURL_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
+    REQUESTS_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
+    PIP_CERT=/opt/corp-ca/ca-bundle.crt
```
[the remark this answers is not in the document]
Comment (jackluo923) [reply components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile]: Not applicable — the centos-stream-9 Dockerfile does not use a multi-stage build with FROM scratch. The ENV persists in the final image.

File: components/core/tools/scripts/corporate-proxy-container.sh [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+    # system certs exist yet (e.g., bare ubuntu:jammy), skip entirely — tools
+    # will fall back to their built-in defaults when the path doesn't exist.
+    if [[ -f /etc/ssl/certs/ca-certificates.crt ]]; then
+        echo "corporate-proxy-container: no corporate CA; copying system certs to /opt/corp-ca/."
+        mkdir -p /opt/corp-ca
+        cp /etc/ssl/certs/ca-certificates.crt /opt/corp-ca/ca-bundle.crt
+    elif [[ -f /etc/pki/tls/certs/ca-bundle.crt ]]; then
+        echo "corporate-proxy-container: no corporate CA; copying system certs to /opt/corp-ca/."
+        mkdir -p /opt/corp-ca
+        cp /etc/pki/tls/certs/ca-bundle.crt /opt/corp-ca/ca-bundle.crt
```
[the remark this answers is not in the document]
Comment (jackluo923) [reply components/core/tools/scripts/corporate-proxy-container.sh]: Addressed in a different way — the no-proxy branch that copied system certs has been removed. The container script now requires a non-empty ca-certificates.crt (staged by the host script or CI workflow), and errors otherwise.

File: components/core/tools/docker-images/clp-env-base-ubuntu-jammy/build.sh [hunk 6]
```diff
@@ -7,8 +7,8 @@ set -o pipefail
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 component_root=${script_dir}/../../../
 
-# Corporate proxy support — see proxy-lib.sh for details.
-source "${script_dir}/../proxy-lib.sh"
+# Corporate proxy support — see corporate-proxy-host.sh for details.
+source "${script_dir}/../../scripts/corporate-proxy-host.sh"
```
[the remark this answers is not in the document]
Comment (jackluo923) [reply components/core/tools/docker-images/clp-env-base-ubuntu-jammy/build.sh:11]: Fixed — updated docs/src/dev-docs/tooling-containers.md to reference corporate-proxy-host.sh.

File: components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile (hunk 4 above)
[the remark this answers is not in the document]
Comment (jackluo923) [reply components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile]: You're right — I was wrong. The CentOS and Ubuntu Dockerfiles do use `FROM scratch` + `COPY --from=base / /`, so ENV vars are lost. Fixed by re-declaring the ENV vars after `FROM scratch` in both Dockerfiles. The manylinux and musllinux Dockerfiles don't flatten, so they're fine.

File: .github/actions/clp-core-build-containers/action.yaml [hunk 7]
```diff
@@ -58,6 +58,28 @@ runs:
...
+            /etc/pki/tls/certs/ca-bundle.crt \
+            /etc/ssl/cert.pem; do
+          if [[ -f "$ca_path" ]]; then
+            cp "$ca_path" "$ca_dest"
+            echo "Staged CA bundle from $ca_path"
+            break
+          fi
+        done
+        if [[ ! -f "$ca_dest" ]]; then
+          echo "ERROR: No system CA bundle found on runner" >&2
```
Comment (junhaoliao) [inline .github/actions/clp-core-build-containers/action.yaml]:
```suggestion
          echo >&2 "ERROR: No system CA bundle found on runner"
```

File: components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile (hunk 4 above)
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile]:
```suggestion
ENV CURL_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
    PIP_CERT=/opt/corp-ca/ca-bundle.crt \
    REQUESTS_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
    SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt
```

File: components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile [hunk 8]
```diff
@@ -59,6 +60,12 @@ RUN ./tools/scripts/lib_install/centos-stream-9/install-all.sh || { \
...
     && rm -rf /tmp/* /var/tmp/*
 
-# Flatten the image
+# Flatten the image (ENV vars don't carry across FROM, so re-declare them).
 FROM scratch
 COPY --link --from=base / /
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
+    CURL_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
+    REQUESTS_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
+    PIP_CERT=/opt/corp-ca/ca-bundle.crt
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile]:
```suggestion
ENV CURL_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
    PIP_CERT=/opt/corp-ca/ca-bundle.crt \
    REQUESTS_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
    SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt
```

File: components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile [hunk 9]
```diff
@@ -59,6 +60,12 @@ RUN ./tools/scripts/lib_install/centos-stream-9/install-all.sh || { \
 RUN dnf clean all \
     && rm -rf /tmp/* /var/tmp/*
 
-# Flatten the image
+# Flatten the image (ENV vars don't carry across FROM, so re-declare them).
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile]:
```suggestion
# Flatten the image
```

File: components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile [hunk 10]
```diff
@@ -59,6 +60,12 @@ RUN ./tools/scripts/lib_install/centos-stream-9/install-all.sh || { \
...
 FROM scratch
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile:63]: to be investigated later - remove flattening?

File: components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile [hunk 11]
```diff
@@ -59,6 +60,12 @@ RUN ./tools/scripts/lib_install/centos-stream-9/install-all.sh || { \
...
 COPY --link --from=base / /
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
+    CURL_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
+    REQUESTS_CA_BUNDLE=/opt/corp-ca/ca-bundle.crt \
+    PIP_CERT=/opt/corp-ca/ca-bundle.crt
+ENV PIPX_BIN_DIR=/usr/local/bin
+ENV PIPX_HOME=/opt/pipx
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-centos-stream-9/Dockerfile:70]: those are fine to keep - just note previously those env variables are not recovered after flattening

File: components/core/tools/docker-images/clp-env-base-manylinux_2_28-aarch64/Dockerfile [hunk 12]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
-    REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt \
-    PIP_CERT=/etc/pki/tls/certs/ca-bundle.crt
+# corporate proxy. See corporate-proxy-host.sh for details.
+RUN ./tools/scripts/corporate-proxy-container.sh
+
+# Point pip/pipx and curl at the corporate CA bundle path set by corporate-proxy-container.sh.
+# This path is outside the system package manager's control, so it survives reinstalls of
+# ca-certificates (which regenerates the system bundle). When no corporate proxy is in use,
+# this path won't exist; tools fall back to their built-in defaults which work fine without a proxy.
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-manylinux_2_28-aarch64/Dockerfile]: ditto - sort

File: components/core/tools/docker-images/clp-env-base-manylinux_2_28-x86_64/Dockerfile [hunk 13]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
-    REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt \
-    PIP_CERT=/etc/pki/tls/certs/ca-bundle.crt
+# corporate proxy. See corporate-proxy-host.sh for details.
+RUN ./tools/scripts/corporate-proxy-container.sh
+
+# Point pip/pipx and curl at the corporate CA bundle path set by corporate-proxy-container.sh.
+# This path is outside the system package manager's control, so it survives reinstalls of
+# ca-certificates (which regenerates the system bundle). When no corporate proxy is in use,
+# this path won't exist; tools fall back to their built-in defaults which work fine without a proxy.
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-manylinux_2_28-x86_64/Dockerfile]: ditto - sort

File: components/core/tools/docker-images/clp-env-base-musllinux_1_2-aarch64/Dockerfile [hunk 14]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
-    REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
-    PIP_CERT=/etc/ssl/certs/ca-certificates.crt
+# corporate proxy. See corporate-proxy-host.sh for details.
+RUN ./tools/scripts/corporate-proxy-container.sh
+
+# Point pip/pipx and curl at the corporate CA bundle path set by corporate-proxy-container.sh.
+# This path is outside the system package manager's control, so it survives reinstalls of
+# ca-certificates (which regenerates the system bundle). When no corporate proxy is in use,
+# this path won't exist; tools fall back to their built-in defaults which work fine without a proxy.
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-musllinux_1_2-aarch64/Dockerfile]: ditto - sort

File: components/core/tools/docker-images/clp-env-base-musllinux_1_2-x86_64/Dockerfile [hunk 15]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
-    REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
-    PIP_CERT=/etc/ssl/certs/ca-certificates.crt
+# corporate proxy. See corporate-proxy-host.sh for details.
+RUN ./tools/scripts/corporate-proxy-container.sh
+
+# Point pip/pipx and curl at the corporate CA bundle path set by corporate-proxy-container.sh.
+# This path is outside the system package manager's control, so it survives reinstalls of
+# ca-certificates (which regenerates the system bundle). When no corporate proxy is in use,
+# this path won't exist; tools fall back to their built-in defaults which work fine without a proxy.
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-musllinux_1_2-x86_64/Dockerfile]: ditto - sort

File: components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile [hunk 16]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
-# Without corporate certs, these paths are the normal system bundles — harmless.
-ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
-    CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
-    REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
-    PIP_CERT=/etc/ssl/certs/ca-certificates.crt
+# Point pip/pipx and curl at the corporate CA bundle path set by corporate-proxy-container.sh.
+# This path is outside the system package manager's control, so it survives reinstalls of
+# ca-certificates (which regenerates the system bundle). When no corporate proxy is in use,
+# this path won't exist; tools fall back to their built-in defaults which work fine without a proxy.
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile]: ditto - sort

File: components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile [hunk 17]
```diff
@@ -59,6 +60,12 @@ RUN ./tools/scripts/lib_install/ubuntu-jammy/install-all.sh || { \
 RUN apt-get clean \
     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
-# Flatten the image
+# Flatten the image (ENV vars don't carry across FROM, so re-declare them).
 FROM scratch
 COPY --link --from=base / /
+ENV SSL_CERT_FILE=/opt/corp-ca/ca-bundle.crt \
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile]: ditto - sort

File: components/core/tools/scripts/corporate-proxy-container.sh [hunk 18]
```diff
@@ -0,0 +1,77 @@
...
+
+if [[ -d /etc/pki/tls/certs ]]; then
+    # RHEL/CentOS/manylinux: also copy to the system bundle for tools that
+    # don't use env vars.
+    cp "$ca_cert" /etc/pki/tls/certs/ca-bundle.crt
+    echo "corporate-proxy-container: installed CA bundle (RHEL/manylinux)."
+else
+    # Debian/Ubuntu/Alpine: also copy to the system bundle for tools that
+    # don't use env vars.
+    mkdir -p /etc/ssl/certs
```
Comment (junhaoliao) [inline components/core/tools/scripts/corporate-proxy-container.sh]:
```suggestion
    mkdir -p "/etc/ssl/certs"
```

File: components/core/tools/scripts/corporate-proxy-container.sh [hunk 19]
```diff
@@ -0,0 +1,77 @@
...
+    cp "$ca_cert" /etc/ssl/certs/ca-certificates.crt
```
Comment (junhaoliao) [inline components/core/tools/scripts/corporate-proxy-container.sh]:
```suggestion
    cp "$ca_cert" "/etc/ssl/certs/ca-certificates.crt"
```

File: components/core/tools/scripts/corporate-proxy-container.sh [hunk 20]
```diff
@@ -0,0 +1,77 @@
...
+
+# Save to a stable path outside the system package manager's control.
+# Tools are pointed here via env vars (SSL_CERT_FILE, PIP_CERT, etc.) so the
+# cert survives later reinstalls of ca-certificates/ca-trust packages.
+cp "$ca_cert" "${corp_ca_bundle}"
+
+if [[ -d /etc/pki/tls/certs ]]; then
+    # RHEL/CentOS/manylinux: also copy to the system bundle for tools that
+    # don't use env vars.
+    cp "$ca_cert" /etc/pki/tls/certs/ca-bundle.crt
```
Comment (junhaoliao) [inline components/core/tools/scripts/corporate-proxy-container.sh]:
```suggestion
    cp "$ca_cert" "/etc/pki/tls/certs/ca-bundle.crt"
```

File: .gitignore [hunk 21]
```diff
@@ -5,4 +5,5 @@ __pycache__/
 .rustfmt.toml
 .task/
 build/
+components/core/tools/scripts/ca-certificates.crt
```
Comment (junhaoliao) [inline .gitignore]: maybe don't add it at the root .gitignore

**Review by junhaoliao — CHANGES_REQUESTED** [review]
the rest lgtm

File: components/core/tools/scripts/corporate-proxy-container.sh [hunk 22]
```diff
@@ -0,0 +1,77 @@
...
+ca_cert="${script_dir}/ca-certificates.crt"
+
+corp_ca_dir="/opt/corp-ca"
+corp_ca_bundle="${corp_ca_dir}/ca-bundle.crt"
+mkdir -p "${corp_ca_dir}"
+
+if [[ ! -s "$ca_cert" ]]; then
+    echo "ERROR: ca-certificates.crt is empty or missing." >&2
+    echo "  Local builds: run build.sh (sources corporate-proxy-host.sh)." >&2
+    echo "  CI builds: ensure the workflow stages a CA bundle." >&2
```
Comment (junhaoliao) [inline components/core/tools/scripts/corporate-proxy-container.sh]:
```suggestion
    echo >&2 "ERROR: ca-certificates.crt is empty or missing."
    echo >&2 "  Local builds: run build.sh (sources corporate-proxy-host.sh)."
    echo >&2 "  CI builds: ensure the workflow stages a CA bundle."
```

File: components/core/tools/scripts/corporate-proxy-host.sh [hunk 23]
```diff
@@ -39,30 +43,37 @@ detect_ca_bundle() {
...
         echo "Corporate proxy support: copying CA bundle from ${ca_bundle}"
         cp "$ca_bundle" "$dest"
     else
-        echo "Corporate proxy support: no CA bundle found on host (no-op)"
-        touch "$dest"
+        echo "ERROR: No CA certificate bundle found on host." >&2
+        echo "  Expected one of:" >&2
+        echo "    /etc/ssl/certs/ca-certificates.crt (Debian/Ubuntu/Alpine)" >&2
+        echo "    /etc/pki/tls/certs/ca-bundle.crt   (RHEL/CentOS)" >&2
+        echo "    /etc/ssl/cert.pem                   (macOS)" >&2
```
Comment (junhaoliao) [inline components/core/tools/scripts/corporate-proxy-host.sh]:
```suggestion
        echo >&2 "ERROR: No CA certificate bundle found on host."
        echo >&2 "  Expected one of:"
        echo >&2 "    /etc/ssl/certs/ca-certificates.crt (Debian/Ubuntu/Alpine)"
        echo >&2 "    /etc/pki/tls/certs/ca-bundle.crt   (RHEL/CentOS)"
        echo >&2 "    /etc/ssl/cert.pem                   (macOS)"
```

File: .gitignore (hunk 21 above)
Comment (jackluo923) [reply .gitignore]: Fixed — moved to components/core/tools/scripts/.gitignore instead.

File: components/core/tools/docker-images/clp-env-base-ubuntu-jammy/build.sh [hunk 24]
```diff
@@ -7,8 +7,8 @@ set -o pipefail
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 component_root=${script_dir}/../../../
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-ubuntu-jammy/build.sh]:
```suggestion
component_root="${script_dir}/../../../"
```

File: components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile [hunk 25]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
 RUN mkdir -p ./tools/scripts/lib_install
 COPY --link ./tools/scripts/lib_install ./tools/scripts/lib_install
+COPY --link ./tools/scripts/corporate-proxy-container.sh ./tools/scripts/corporate-proxy-container.sh
+COPY --link ./tools/scripts/ca-certificates.crt ./tools/scripts/ca-certificates.crt
 # Corporate proxy support: install host CA certificates into the container's
 # trust store so tools like curl and apt can verify TLS through intercepting
 # proxies (e.g., Zscaler, Fortinet, Palo Alto). No-op when not behind a
-# corporate proxy. See proxy-lib.sh for details.
-RUN ./tools/scripts/lib_install/setup-corporate-proxy.sh
+# corporate proxy. See corporate-proxy-host.sh for details.
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile]: should update the comments since now that the scripts aren't no-ops

File: components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile [hunk 26]
```diff
@@ -6,21 +6,22 @@ WORKDIR /root
...
-# updating the system trust store above. These env vars override that behavior.
-# Without corporate certs, these paths are the normal system bundles — harmless.
-ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
-    CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
-    REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
-    PIP_CERT=/etc/ssl/certs/ca-certificates.crt
+# Point pip/pipx and curl at the corporate CA bundle path set by corporate-proxy-container.sh.
+# This path is outside the system package manager's control, so it survives reinstalls of
+# ca-certificates (which regenerates the system bundle). When no corporate proxy is in use,
+# this path won't exist; tools fall back to their built-in defaults which work fine without a proxy.
```
Comment (junhaoliao) [inline components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile]: ditto - should update the comments since now that the scripts aren't no-ops

**Review by junhaoliao — CHANGES_REQUESTED** [review]
the common filters in `.github/workflows/clp-artifact-build.yaml` should be updated to include the scripts added in this PR as well

**Comment by jackluo923** [comment]
> the common filters in `.github/workflows/clp-artifact-build.yaml` should be updated to include the scripts added in this PR as well

done

**Review by junhaoliao — APPROVED** [review]
for the pr title, how about
```
fix(docker): Remove `update-ca-trust`/`update-ca-certificates` dependency in corporate proxy CA setup (fixes #2116).
```
