### PR TITLE
ci(clang-format): Update to clang-format v19 (and the corresponding yscope-dev-utils) and apply the corresponding formatting changes (fixes #545).

### LINKED ISSUE #545: lint workflow failed due to clang-format warnings
### Bug

The recent lint workflows failed due to clang-format warnings:
https://github.com/y-scope/clp/actions/runs/11006755921

This is because clang-format released version 19.1 in PyPI, which changed code formatting behavior.

### CLP version

3ceb17ee51cc91026f156ce5b1905f84ef18d7a9

### Environment

GitHub CI

### Reproduction steps

Run lint workflow

### PR DESCRIPTION
**Pull request by LinZhihao-723**
# Description

This PR updates yscope-dev-utils to the latest commit so that clang-format v19 config can be used. It also updates clang-format version to v19 in the linter dependency to format C++ code using the latest clang-format pypi release.

# Validation performed

- Ensure workflows all passed.

## Release Notes

- **Style**
    - Standardized method signature formatting across multiple components
    - Removed unnecessary semicolons from constructors
    - Improved code readability by adjusting line breaks in function declarations

- **Dependency Updates**
    - Upgraded `clang-format` version requirement to >=19.1.6

- **Subproject Updates**
    - Updated `tools/yscope-dev-utils` subproject reference

These changes primarily focus on code style consistency and minor dependency management, with no significant functional modifications to the codebase.

### CODE REVIEW

File: components/core/src/clp/ffi/ir_stream/ir_unit_deserialization_methods.cpp [hunk 1]
```diff
@@ -142,8 +139,7 @@ deserialize_int_val(ReaderInterface& reader, encoded_tag_t tag, value_int_t& val
  * @return Forwards `deserialize_encoded_text_ast`'s return values on failure.
  */
 template <typename encoded_variable_t>
-requires(std::is_same_v<ir::four_byte_encoded_variable_t, encoded_variable_t>
-         || std::is_same_v<ir::eight_byte_encoded_variable_t, encoded_variable_t>)
+requires(std::is_same_v<ir::four_byte_encoded_variable_t, encoded_variable_t> || std::is_same_v<ir::eight_byte_encoded_variable_t, encoded_variable_t>)
```
Comment (kirkrodrigues) [inline components/core/src/clp/ffi/ir_stream/ir_unit_deserialization_methods.cpp:142]: Add extra `()` to work around `clang-format` limitations.

File: components/core/src/clp/ffi/ir_stream/ir_unit_deserialization_methods.cpp [hunk 2]
```diff
@@ -398,8 +394,7 @@ auto deserialize_value_and_insert_to_node_id_value_pairs(
 }
 
 template <typename encoded_variable_t>
-requires(std::is_same_v<ir::four_byte_encoded_variable_t, encoded_variable_t>
-         || std::is_same_v<ir::eight_byte_encoded_variable_t, encoded_variable_t>)
+requires(std::is_same_v<ir::four_byte_encoded_variable_t, encoded_variable_t> || std::is_same_v<ir::eight_byte_encoded_variable_t, encoded_variable_t>)
```
Comment (kirkrodrigues) [inline components/core/src/clp/ffi/ir_stream/ir_unit_deserialization_methods.cpp:397]: Add extra `()` to work around `clang-format` limitations.

File: components/core/tests/test-ffi_KeyValuePairLogEvent.cpp [hunk 3]
```diff
@@ -45,10 +45,9 @@ constexpr std::string_view cStringToEncode{"uid=0, CPU usage: 99.99%, \"user_nam
  * @return The encoded result.
  */
 template <typename encoded_variable_t>
-requires(std::is_same_v<encoded_variable_t, eight_byte_encoded_variable_t>
-         || std::is_same_v<encoded_variable_t, four_byte_encoded_variable_t>)
-[[nodiscard]] auto get_encoded_text_ast(std::string_view text
-) -> clp::ir::EncodedTextAst<encoded_variable_t>;
+requires(std::is_same_v<encoded_variable_t, eight_byte_encoded_variable_t> || std::is_same_v<encoded_variable_t, four_byte_encoded_variable_t>)
```
Comment (kirkrodrigues) [inline components/core/tests/test-ffi_KeyValuePairLogEvent.cpp:48]: Add extra `()` to work around `clang-format` limitations.

File: components/core/tests/test-ffi_KeyValuePairLogEvent.cpp [hunk 4]
```diff
@@ -102,8 +101,7 @@ auto insert_invalid_node_id_value_pairs_with_node_type_errors(
 ) -> bool;
 
 template <typename encoded_variable_t>
-requires(std::is_same_v<encoded_variable_t, eight_byte_encoded_variable_t>
-         || std::is_same_v<encoded_variable_t, four_byte_encoded_variable_t>)
+requires(std::is_same_v<encoded_variable_t, eight_byte_encoded_variable_t> || std::is_same_v<encoded_variable_t, four_byte_encoded_variable_t>)
```
Comment (kirkrodrigues) [inline components/core/tests/test-ffi_KeyValuePairLogEvent.cpp:104]: Add extra `()` to work around `clang-format` limitations.

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

File: components/core/src/clp/ffi/ir_stream/ir_unit_deserialization_methods.cpp (hunk 1 above)
Comment (LinZhihao-723) [reply components/core/src/clp/ffi/ir_stream/ir_unit_deserialization_methods.cpp:142]: gg mb, didn't realize it exceeds the line limit
