### PR TITLE
Don't set timestamp format when splitting a timestamp-less file (fixes #167).

### LINKED ISSUE #167: Decompression fails on one specific large file with long lines
### Bug

Using the heuristic to compress and decompress Loghub-datasets/Loghub-datasets/HDFS_1/HDFS.log results in a decompressed file that does not match the original.

### CLP version

c2e5823a8b1f6a38b26e7956c31595cf36f6edd2

### Environment

Ubuntu 20.04

### Reproduction steps

Compress using the heuristic
Decompress the resulting archive
Diff decompressed file with original file

### PR DESCRIPTION
**Pull request by davemarco**
# References
fixes issue #167 

# Description

**Summary of issue:**

When compressing/decompressing Loghub dataset, one file without timestamps had logs out-of-order when compared to original dataset. Out-of-order logs were a result of compressing some logs to the incorrect segment. Specifically logs were being compressed into `m_segment_for_files_with_timestamp` instead of `m_segment_for_files_without_timestamp`.

For large files, the [split_file function][1] is called, which then calls [change_ts_pattern function][2], where there is a bug. The function is meant to pass timestamps from the first chunk of the file, to the second chunk, but if there is no timestamp, it passes an unintialized timestamp object. This is the bug, it should pass nothing for files without timestamps. Clp incorrectly believes the uninitialized timestamp object is a real timestamp, and the second chunk is compressed into `m_segment_for_files_with_timestamp` instead of `m_segment_for_files_without_timestamp`. The segment with timestamps is decompressed first leading to out-of-order logs. 

**Fix:**
Restructure [change_ts_pattern function][3] to do nothing if the file has no timestamps

**Discussion Topic:**
A similar issue may arise if a large log file has a large chunk of logs without timestamps followed by logs with timestamps. Not sure this is a realistic scenario, but noting here in case relevant. 

[1]: https://github.com/davemarco/clp/blob/9f7cc0363466e24f9da1db7e90dc8bad9651f991/components/core/src/clp/streaming_archive/writer/utils.cpp#L21C1-L36C2
[2]: https://github.com/davemarco/clp/blob/9f7cc0363466e24f9da1db7e90dc8bad9651f991/components/core/src/clp/streaming_archive/writer/File.cpp#L87
[3]: https://github.com/davemarco/clp/blob/8a49cb09c238169b85e4b27844f1fa4746a37dc0/components/core/src/clp/streaming_archive/writer/File.cpp#L87

# Validation performed
Compressed/decompressed entire dataset. Ran diff recursively on compressed/decompressed dataset with no differences vs. original.

### CODE REVIEW

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]
Nice find and thanks for the contribution!

Instead of making `File::change_ts_pattern` resistant to null timestamp patterns, what if we made the call to `Archive::change_ts_pattern` conditional on the last file's timestamp pattern being non-null? Your fix works currently, but relies on the (current) assumption that once a file has a timestamp it will continue to have a timestamp. However, one day this may not be true, for instance if we stop being able to recognize the timestamp. If this happens currently, we will treat all log un-timestamped messages as being part of the previous message (which can easily break). So in the future, we will probably handle this case by allowing a file to drop its timestamp format.

As for the issue about splits not being decompressed in order since the timestamped and un-timestamped segments are built in parallel (and thus we can't rely on their sequential order for decompression), we should open an issue for that.

**Comment by davemarco** [comment]
I made the call to `Archive::change_ts_pattern` in `streaming_archive::writer::split_file` be conditional on `streaming_archive::writer::File:has_ts_pattern`. In short, it checks if the file has timestamps before passing timestamps to the next file. Files with no timestamps will not receive an empty timestamp since the function is not called.

File: components/core/src/clp/streaming_archive/writer/utils.cpp [hunk 1]
```diff
@@ -25,14 +25,17 @@ auto split_file(
...
+    auto has_ts_pattern = encoded_file.has_ts_pattern();
     auto orig_file_id = encoded_file.get_orig_file_id();
     auto split_ix = encoded_file.get_split_ix();
     archive_writer.set_file_is_split(true);
     close_file_and_append_to_segment(archive_writer);
 
     archive_writer.create_and_open_file(path_for_compression, group_id, orig_file_id, ++split_ix);
-    // Initialize the file's timestamp pattern to the previous split's pattern
-    archive_writer.change_ts_pattern(last_timestamp_pattern);
+    if (true == has_ts_pattern) {
```
Comment (kirkrodrigues) [inline components/core/src/clp/streaming_archive/writer/utils.cpp:35]:
```suggestion
    if (has_ts_pattern) {
```

We only require the `false == condition` pattern to avoid `!condition` (since in the past some devs have missed the `!`, lol).

File: components/core/src/clp/streaming_archive/writer/utils.cpp [hunk 2]
```diff
@@ -51,8 +55,10 @@ auto split_file_and_archive(
     split_archive(archive_user_config, archive_writer);
 
     archive_writer.create_and_open_file(path_for_compression, group_id, orig_file_id, ++split_ix);
-    // Initialize the file's timestamp pattern to the previous split's pattern
-    archive_writer.change_ts_pattern(last_timestamp_pattern);
+    if (true == has_ts_pattern) {
```
Comment (kirkrodrigues) [inline components/core/src/clp/streaming_archive/writer/utils.cpp:58]:
```suggestion
    if (has_ts_pattern) {
```

**Review by kirkrodrigues — CHANGES_REQUESTED** [review]

**Review by kirkrodrigues — APPROVED** [review]
