### PR TITLE
fix(webui): Cap compression metadata query results to prevent OOM crash (fixes #2040).

### LINKED ISSUE #2040: OOM issue in CLP webUI
### Bug

Hi Team, 

Getting below error :

<--- Last few GCs --->

[1:0x446fd000] 2018900739 ms: Mark-Compact 4047.3 (4135.6) -> 4046.9 (4135.6) MB, pooled: 0 MB, 745.14 / 0.00 ms  (average mu = 0.626, current mu = 0.146) allocation failure; scavenge might not succeed
[1:0x446fd000] 2018902357 ms: Mark-Compact 4062.6 (4135.6) -> 4062.2 (4166.6) MB, pooled: 0 MB, 1586.82 / 0.00 ms  (average mu = 0.307, current mu = 0.019) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xe36068 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/opt/clp/bin/node-22]
 2: 0x1202550 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/clp/bin/node-22]
 3: 0x1202827 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/clp/bin/node-22]
 4: 0x1430105  [/opt/clp/bin/node-22]
 5: 0x1449999 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/clp/bin/node-22]
 6: 0x141e048 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/clp/bin/node-22]
 7: 0x141ef75 v8::inte

Can you please help troubleshoot this ?

some short term fix for getting unblocked as well as long term path.

### CLP version

v0.8.0

### Environment

Amazon Linux

### Reproduction steps

Issue happening while opening CLP web ui

-> We were not running queries frequently.

### PR DESCRIPTION
**Pull request by junhaoliao**
# Description

Add a `LIMIT 1000` clause and remove the `WHERE ... INTERVAL 30 DAY` filter
from the compression metadata SQL query to prevent the webui Node.js server
from running out of memory when the `compression_jobs` table contains a large
number of rows.

Previously, `getCompressionMetadataQuery()` fetched **all** compression jobs
updated within the last 30 days with no row limit:

https://github.com/y-scope/clp/blob/8efbadd850cc9977e0947e36bb33537253b5a263/components/webui/server/src/routes/api/compress-metadata/sql.ts#L26-L40

When a user navigates to the Ingest page, the client calls
`GET /api/compress-metadata`, which executes this query, loads every row into
memory, and brotli-decompresses + msgpack-decodes the `clp_config` VARBINARY
blob for each row. With a large number of jobs (e.g., 5 million), this exhausts
the V8 heap (~4 GiB default) and crashes the server with:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

The fix:
1. Introduces `COMPRESSION_METADATA_QUERY_LIMIT = 1000` and appends
   `LIMIT 1000` to the query.
2. Removes the `WHERE update_time >= NOW() - INTERVAL 30 DAY` clause since the
   `LIMIT` already caps the result set and the time filter is redundant when
   ordering by `id DESC`.

Since the query orders by `id DESC`, the 1000 most recent jobs are returned
regardless of their update time.

# Impact Assessment

- **Affected component**: `webui` server -- compression metadata API route.
- **Root cause**: Unbounded `SELECT` query on the `compression_jobs` table with
  no `LIMIT` clause.
- **Fix**: Cap the result set to 1000 rows and remove the redundant time filter.
- **Scope**: Only one query is affected. All other SQL queries in the webui
  server were audited -- they are either aggregation queries (returning 1 row),
  filtered by primary key, or return small metadata (dataset names, column
  names).
- **Risk**: Low. The `ORDER BY id DESC` already exists, so the 1000 most recent
  jobs are always returned. Users with more than 1000 jobs will see only the
  latest 1000 in the Ingest page's Compression Jobs table.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

## 1. Build the CLP package

**Task**: Build the CLP package (including the Docker image) with the fix
applied.

**Command**:
```shell
task package
```

**Output** (last lines):
```
task: [package] rsync --archive "tools/deployment/package/" "/home/junhao/workspace/2-clp/build/clp-package"
task: [package] rsync --archive "/home/junhao/workspace/2-clp/build/clp-package-image.id" "/home/junhao/workspace/2-clp/build/clp-package"
task: [package] echo '0.9.1-dev' > '/home/junhao/workspace/2-clp/build/clp-package/VERSION'
```

## 2. Verify the LIMIT clause is present and the WHERE clause is absent in the Docker image

**Task**: Confirm the compiled JavaScript inside the freshly built Docker image
includes the LIMIT clause and does not include the WHERE time filter.

**Command**:
```shell
IMAGE_ID=$(cat build/clp-package/clp-package-image.id)
docker run --rm --entrypoint cat "$IMAGE_ID" \
    /opt/clp/var/www/webui/server/dist/src/routes/api/compress-metadata/sql.js
```

**Output** (relevant portion):
```
const COMPRESSION_METADATA_QUERY_LIMIT = 1000;
const getCompressionMetadataQuery = () => `
    SELECT
        ...
    FROM ${settings.SqlDbCompressionJobsTableName}
    ORDER BY ${COMPRESSION_JOBS_TABLE_COLUMN_NAMES.ID} DESC
    LIMIT ${COMPRESSION_METADATA_QUERY_LIMIT};
`;
```

**Explanation**: The `WHERE ... INTERVAL 30 DAY` clause is absent and
`LIMIT ${COMPRESSION_METADATA_QUERY_LIMIT}` (1000) is present.

## 3. Start CLP and insert 5,000,000 compression job records

**Task**: Reproduce the conditions that trigger the OOM crash.

**Commands**:
```shell
cd build/clp-package
./sbin/start-clp.sh
```

**Output** (last line):
```
2026-02-26T20:38:52.630 INFO [controller] Started CLP.
```

Then insert 5,000,000 rows with `status = 2` (SUCCEEDED) and valid
brotli-compressed msgpack `clp_config` blobs (matching `ClpIoPartialConfigSchema`)
into `compression_jobs`:

```python
# (abbreviated -- batch inserts of 10,000 rows at a time)
total = 5000000
# ...
cursor.executemany(insert_sql, batch_data)
```

**Output**:
```
Inserted 500000/5000000 rows (11.6s)
...
Inserted 5000000/5000000 rows (105.7s)
Done: inserted 5000000 rows in 105.7s
Total rows in compression_jobs: 5000000
```

## 4. Verify `GET /api/compress-metadata/` returns 1000 rows without crash

**Task**: Confirm the API returns a bounded result set and the server stays
healthy.

**Command**:
```shell
curl -s -o /tmp/resp.json -w "%{http_code}" http://127.0.0.1:4000/api/compress-metadata/
python3 -c "import json; data=json.load(open('/tmp/resp.json')); print(len(data))"
docker stats --no-stream --format "{{.MemUsage}}" clp-package-04a1-webui-1
```

**Output**:
```
200
1000
67.7MiB / 58.64GiB
```

**Explanation**: The API returned HTTP 200 with exactly 1000 rows (the LIMIT).
Memory usage stayed at ~68 MiB. No `FATAL ERROR` in the container logs.

## 5. Verify the Ingest page loads successfully

**Task**: Confirm the Ingest page loads without crashing the server.

**Command**:
```shell
curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:4000/ingest
```

**Output**:
```
200
```

**Explanation**: The Ingest page returned HTTP 200. The webui server remained
healthy throughout with no OOM errors in the container logs:

```shell
docker logs clp-package-04a1-webui-1 2>&1 | grep -i "FATAL\|heap out of memory\|OOM"
# (no output -- no OOM errors)
```

## 6. Confirm the OOM crash is reproducible on `main` (before the fix)

**Task**: Verify that the same 5,000,000-row scenario crashes the server on the
unfixed `main` branch.

**Output** (before fix, same 5M rows, no `NODE_OPTIONS` hack):
```
[1:0x19c7b000]   242039 ms: Mark-Compact 4021.4 (4129.2) -> 4005.8 (4129.4) MB, pooled: 3 MB,
    868.66 / 0.76 ms  (average mu = 0.093, current mu = 0.040) allocation failure;
    scavenge might not succeed
[1:0x19c7b000]   242929 ms: Mark-Compact 4021.8 (4129.7) -> 4006.2 (4129.9) MB, pooled: 2 MB,
    853.99 / 0.83 ms  (average mu = 0.068, current mu = 0.040) allocation failure;
    scavenge might not succeed

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Explanation**: Without the fix, the V8 heap climbed to ~4 GiB (the default
limit) and crashed after ~4 minutes. Memory growth was observed at
2.3 -> 3.6 -> 4.0 -> 4.6 -> 5.0 -> 5.4 GiB (container RSS) before the fatal
error.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

### CODE REVIEW

File: components/webui/server/src/routes/api/compress-metadata/sql.ts [hunk 1]
```diff
@@ -36,7 +38,8 @@ const getCompressionMetadataQuery = () => `
         ${COMPRESSION_JOBS_TABLE_COLUMN_NAMES.CLP_CONFIG}
     FROM ${settings.SqlDbCompressionJobsTableName}
     WHERE ${COMPRESSION_JOBS_TABLE_COLUMN_NAMES.UPDATE_TIME} >= NOW() - INTERVAL 30 DAY
```
Comment (junhaoliao) [inline components/webui/server/src/routes/api/compress-metadata/sql.ts]: thoughts on removing this 30 day check? actually, is there a reason we previously prefer it over the numeric count?

**Review by hoophalab — DISMISSED** [review]

File: components/webui/server/src/routes/api/compress-metadata/sql.ts (hunk 1 above)
Comment (hoophalab) [reply components/webui/server/src/routes/api/compress-metadata/sql.ts]: There probably isn't a real reason. It's an arbitrary decision from the initial commit.

**Review by hoophalab — APPROVED** [review]
