### PR TITLE
fix(webui): Add absolute path validation to compression paths input (fixes #1702).

### LINKED ISSUE #1702: webui: Local compression job submission only supports absolute paths and allows empty paths
### Bug

The compression job submission form doesn't support paths like:

* `logs/mongod.jsonl`
* `~/logs/mongod.jsonl`

These will cause the compression job to fail.

The form also allows input like:

```text

```

(i.e., empty lines). This compression job will succeed but should've probably been rejected as invalid input in the UI.

### CLP version

e6d7a58

### Environment

* Ubuntu 22.04.5
* Docker version 28.4.0, build d8eb465
* Package: clp-json

### Reproduction steps

Use inputs like the ones shown above.

### PR DESCRIPTION
**Pull request by junhaoliao**
# Description

This change introduces validation for absolute file system paths in compression job
submission workflows.

Changes include:

* Adding `AbsolutePathSchema` to constrain values to non-empty strings beginning with `/`.
* Updating `CompressionJobCreationSchema` so `paths` is now an array of `AbsolutePathSchema` with
  `minItems: 1`.
* Adding `validateAbsolutePaths` to the ingest page to validate each line of multiline input.
* Replacing the old required-rule check with a custom validator that provides line-specific error
  messages.
* Updating the placeholder text to clarify that only absolute paths are valid.

These updates ensure that only valid absolute paths can be submitted, preventing backend errors and
improving user feedback.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

1. Manually tested frontend validation in the ingestion UI:
   * Entered valid absolute paths:
     * `/var/log/syslog`
     * `/home/samples`
     * Empty lines mixed with valid paths
   * Verified that form submission succeeded with no validation errors.
2. Tested invalid values:
   * Relative paths (`logs/syslog`)
   * Paths with tildes (`~/samples`)
   * Lines containing only whitespace
   * Verified error messages referenced correct line number and blocked submission.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

* **Bug Fixes**
  * Per-line validation for path inputs: ignores blank lines and shows a clear, line-specific error for the first non-absolute path.

* **New Features**
  * Forms now require at least one absolute path (one per line) and include an updated placeholder guiding users to enter absolute paths on the server host.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx [hunk 1]
```diff
@@ -13,11 +43,22 @@ const PathsInputFormItem = () => (
     <Form.Item
         label={"Paths"}
         name={"paths"}
-        rules={[{required: true, message: "Please enter at least one path"}]}
+        rules={[
+            {
+                // The `validator` function expects a `Promise` to be returned.
+                // eslint-disable-next-line @typescript-eslint/require-await
+                validator: async (_, value?: string) => {
+                    const error = validateAbsolutePaths(value ?? "");
```
Comment (davemarco) [inline components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx]: I think they want you to use promises. Maybe look at the example here https://ant.design/components/form#form-demo-register.

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx [hunk 2]
```diff
@@ -13,11 +43,22 @@ const PathsInputFormItem = () => (
...
+                        throw new Error(error);
+                    }
+                },
+            },
+        ]}
     >
         <Input.TextArea
             autoSize={{minRows: 4, maxRows: 10}}
-            placeholder={"Enter paths to compress, one per line"}/>
+            placeholder={"Enter absolute paths to compress, one per line"}/>
```
Comment (davemarco) [inline components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx]:
```suggestion
            placeholder={"Enter absolute paths on server to compress, one per line"}/>
```

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx [hunk 3]
```diff
@@ -13,11 +43,22 @@ const PathsInputFormItem = () => (
     <Form.Item
         label={"Paths"}
         name={"paths"}
-        rules={[{required: true, message: "Please enter at least one path"}]}
+        rules={[
```
Comment (davemarco) [inline components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx:18]: maybe leave the rule, and just add the white space flag
Screenshot 2025-12-01 at 1 37 23 PM

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx (hunk 2 above)
Comment (davemarco) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx]: not related to PR but i think more clear for users.

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx (hunk 3 above)
Comment (davemarco) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx:18]: then we might not need the check at the end as well. Since it would be redundant

**Review by davemarco — CHANGES_REQUESTED** [review]
small comments

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx (hunk 2 above)
Comment (junhaoliao) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx]: how about
```suggestion
            placeholder={"Enter absolute paths on the server host, one per line"}/>
```

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx (hunk 3 above)
Comment (junhaoliao) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx:18]: good point. let me try

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx (hunk 1 above)
Comment (junhaoliao) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx]: if i'm not wrong, the `async` syntax is also returning promises and cleaner to write / read. in fact, the `async` syntax enforces only Promises can be returned

similarly, if anything is thrown in the async function, promise rejections are automatically created

File: components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx (hunk 3 above)
Comment (junhaoliao) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx:18]: not sure how, but it seems once a validator is defined, any other fields in the rule are ignored

Comment (junhaoliao) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx:18]: actually let me try another approach

Comment (davemarco) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx:18]: Screenshot 2025-12-01 at 6 18 01 PM
Something like this dosent work?

Comment (junhaoliao) [reply components/webui/client/src/pages/IngestPage/Compress/PathsInputFormItem.tsx:18]: splitting the rules works, but the whitespace thing we actually need to set it to `true` to prohibit whitespaces lol (like i thought setting `whitespace: false` would be more intuitive

anyways it's all good for review now

**Review by davemarco — CHANGES_REQUESTED** [review]
mostly lgtm, do u want to move ur validator to my new validate.ts file after you merge main? then i will approve

**Review by davemarco — DISMISSED** [review]
lgtm

**Review by davemarco — APPROVED** [review]
lgtm
